### ISSUE TITLE
Autocomplete path

### ISSUE THREAD

**Issue by metalelf0** [mhinz/vim-grepper#1]
First of all, thanks a lot for sharing this, the plugin looks awesome and I think it has a bright future ahead.

Now, I have a question. I'm quite used to hit tab to autocomplete the path of my search location. My typical flow is: `:Ag "Search query" some<tab>where/in/my/pro<tab>ject/<CR>`.

With `vim-grepper`, I have to type the whole path: `gs -> "Search query" somewhere/in/my/project<CR>`, because hitting `<tab>` changes the search program. How could I get the path to autocomplete?

Thanks and keep up the great work! :+1:

**Comment by mhinz** [comment]
Thanks! I'm glad if other people find my plugins useful, too.

Now we dive into the ugly corners of Vim. ;] File completion for a command works different from file completion of a function like `input()`, like in this case.

For `ag.vim`'s case it's easy enough. You can simply test this:

```vim
:command! -nargs=* -complete=file Edit edit <q-args>`
```
Afterwards you can use tab completion _anywhere_ after `:Edit ` and it will just work. For `input()` you have to write an own completion function and even then, the completion functions always replaces the whole line. That works, but it has the disadvantage that, if it shows the possible completions, you'll also see all leading context that possible doesn't even belong to the path.

Anyway, it's better than no file completion at all, I guess. I'll keep my eyes open for better solutions, though.

**Comment by metalelf0** [comment]
Wow, works great! I also really like the new mappings. Great work, man! :) :+1:

**Comment by mhinz** [comment]
Thanks!

**Comment by mhinz** [comment]
@metalelf0 By the way, this will probably be useful for you: #6.
