### ISSUE TITLE
Possible issue with jobstart's response newlines?

### ISSUE THREAD

**Issue by azure-satellite** [mhinz/vim-grepper#10]
Sometimes newlines don't get parsed correctly. I wish I could give steps to reproduce but I would have to investigate more. Opening in case someone experiences the same problem and can provide more information.

Possibly related? https://github.com/neovim/neovim/issues/1574

![screen shot 2015-09-14 at 6 12 17 pm 2](https://cloud.githubusercontent.com/assets/4336260/9863232/29da94d2-5b0c-11e5-8507-dce9cd4ba702.png)

**Comment by mhinz** [comment]
Hey, sorry for the late response, but I was on a longer trip.

What do I have to look at in that screenshot?

**Comment by azure-satellite** [comment]
Thanks for ocaml :) The issue was that when `grepformat` is wrong, you see those `||` lines at the beginning. I know for a fact that the error format wasn't wrong, because it worked in vim, but in neovim it didn't sometimes. I thought I had read something about newlines issues with jobcontrol so I linked it in case it might be useful.

**Comment by mhinz** [comment]
Hmm, maybe it's related to this commit that was merged yesterday: https://github.com/jbradaric/vim-grepper/commit/6102a9b260322b607f584e99a4793901bfbc5f59

It would be nice if you could leave a note here, if it happens again (after you updated of course). :-)

**Comment by azure-satellite** [comment]
That seems to do it. Thanks!

**Comment by mhinz** [comment]
Awesome! Thanks for the feedback.
