### ISSUE TITLE
Quickfix window height

### ISSUE THREAD

**Issue by yevhen-m** [mhinz/vim-grepper#100]
How can I turn off adjustment of quickfix window height? I prefer it to be always the same size, so I can easily catch its first line with my eyes.

**Comment by mhinz** [comment]
You could put this in your vimrc:

```vim
autocmd User Grepper copen
let g:grepper = { 'open': 0 }
```

**Comment by yevhen-m** [comment]
@mhinz thanks, it works. Btw, I enjoy `Grepper` very much, thanks.

**Comment by mhinz** [comment]
Thanks, I'm glad you like it.

I added that question to `:h startify-faq`.
