### ISSUE TITLE
Search in specific directory

### ISSUE THREAD

**Issue by yevhen-m** [mhinz/vim-grepper#108]
There is currently `-dir` flag, which helps manipulate search dir.

1. Could you please add a setting to autochange directory back after this flag with `file` value was used?
2. Have you ever though about providing ability to search in a directory, specified in args?

I often want to search in a specific directory (not changing vim's `cwd`), but currently there is no quick way to do this ((.

**Comment by mhinz** [comment]
1. Unfortunately it's not as easy as it seems, because even when you switch back, the quickfix entries won't adapt which leads to issues. See https://github.com/mhinz/vim-grepper/issues/83#issuecomment-296369569.
1. Can't be done without solving (1) first.

CC @lbonn :)

**Comment by mhinz** [comment]
Disclaimer: I'm a bit short of time lately, so I usually only work on issues that I experience myself, so.. if either of you wants to have a go at it, I'll gladly grant you commit rights!

**Comment by lbonn** [comment]
I was planning to work on this soon, when I'll have some spare hours (next train trip maybe?). But if someone wants to do it, that's fine too.

**Comment by yevhen-m** [comment]
Thanks, but I'm not skilled enough to implement these features. So @lbonn, I wish you a lovely train trip )))).

**Comment by lbonn** [comment]
Another approach which already works: use `:Grepper -dir file` from a directory explorer such as dirvish or the default netrw.

If you'd prefer to choose the directory from the vim command line, the option could be named `-cd`.

**Comment by binguea** [comment]
I have the same need as yevhen-m, to search in a particular directory (project root). I implemented an enhancement (PR#111) for that.

It's not as flexible as being able to use a different directory for each grep action. But it works for my need, that I always want to grep from the project root directory, and I need a way to tell where is the project root. If PR#111 is accepted, you can add a setting:

```
let g:grepper.repo=['.project', '.git', '.SVN']
let g:grepper.dir='repo,file'
```

Then put a file `.project` in your project root.

Hope this would help you too.

**Comment by mhinz** [comment]
`g:grepper.repo` is now in master.

@yevhen-m Would the approach mentioned by binguea work for you?

**Comment by mhinz** [comment]
1. Implemented!
1. Somewhat implemented. (No need for to make the code any more complicated for something that can be achieved by simply switching directories first. Or using the variant binguea mentioned above.)

Closing.
