### ISSUE TITLE
cmdline mappings mess up history

### ISSUE THREAD

**Issue by Konfekt** [mhinz/vim-grepper#113]
With 
```vim
call plug#begin('~/.vim/plugged')
  Plug 'https://github.com/mhinz/vim-grepper'
  Plug 'https://github.com/vim-scripts/cmdline-completion'
call plug#end()

filetype plugin indent on
syntax enable

cnoremap <SID>(up)   <up><home>
cmap     <expr>   <C-n> getcmdpos() == 1 ? '<SID>(up)' : '<Plug>CmdlineCompletionForward'
```
as `.vimrc`, hitting `<c-p>` after `:Grepper` does not yield any matches, even if the same string in the same directory with the same searchtool and paramters did so before. Also, say `foo` was searched. Then `$$$cr###foo` appears in the history.

**Comment by mhinz** [comment]
1. What is `<sid>(up)`?
1. Can you reproduce it without those mappings and the cmdline-completion plugin?

**Comment by Konfekt** [comment]
1. It is the mapping `cnoremap <SID>(up)   <up><home>`
2. Yes, by 
```vim
cnoremap <SID>(up)      <up><home>
cnoremap <SID>(CtrlK)   <c-k>
cmap     <expr>   <C-k> getcmdpos() == 1 ? '<SID>(up)' : '<SID>(CtrlK)'
```
and hitting `<ctrl-k>` after `:Grepper`.

**Comment by mhinz** [comment]
Here's what I tried (note that I added `set nocompatible` to the config):

![](https://i.imgur.com/TINyPBM.gif)

In the end I use `<c-k>` multiple times to get the previous commands.

**Comment by Konfekt** [comment]
The issue is about 
- first `:Grepper`, searching for  `foo`, and 
- then `:Grepper<cr>` and hitting `<c-k>` to search for `foo` again.

Suddenly there are no matches anymore because `foo` turned into `$$$cr###foo`.

**Comment by mhinz** [comment]
Here's the exact config I use:

```vim
" vimrc

set nocompatible

call plug#begin('~/.vim/plugged')
  Plug 'https://github.com/junegunn/vim-plug'
  Plug 'https://github.com/mhinz/vim-grepper'
  Plug 'https://github.com/vim-scripts/cmdline-completion'
call plug#end()

filetype plugin indent on
syntax enable

cnoremap <SID>(up)      <up><home>
cnoremap <SID>(CtrlK)   <c-k>
cmap     <expr>   <C-k> getcmdpos() == 1 ? '<SID>(up)' : '<SID>(CtrlK)'
```

And I run it via `vim -i NONE -u vimrc vimrc`. Can you try the exact same steps? It all seems to work for me:

![](https://i.imgur.com/CH9goXl.gif)

For reference, the code that is supposed to handle this is [here](https://github.com/mhinz/vim-grepper/blob/master/autoload/grepper.vim#L599-L603) and [here](https://github.com/mhinz/vim-grepper/blob/master/autoload/grepper.vim#L540).

**Comment by Konfekt** [comment]
Followed by `:Grepper<cr>`, `foo<cr>`, `:Grepper<cr>` and `<c-k><cr>`

**Comment by Konfekt** [comment]
I also commented out `/etc/vimrc` which didn't make a difference. The Vim version is VIM - Vi IMproved 8.0 (2016 Sep 12), Included patches: 1-566

**Comment by mhinz** [comment]
Does the same happenw with `:Grepper<cr>`, `<up>`?

**Comment by Konfekt** [comment]
Looking at your gif, something is off: After `:Grepper<cr>`, `foo<cr>` and `:Grepper<cr>`, now `<c-k>` should give `foo` but `bar` it is ? Also, you already see flashing up that `foo` is saved as `###foo$$$`.

**Comment by Konfekt** [comment]
No, with `<up>` everything is fine as it is not remapped. Only `<c-k>` is.

**Comment by mhinz** [comment]
> Looking at your gif, something is off: After :Grepper<cr>, foo<cr> and :Grepper<cr>, now <c-k> should give foo but bar it is ?

No, I do `:Grepper<cr>`, `foo<cr>`, `:Grepper<cr>`, `bar<cr>`, `:Grepper<cr>`, `<c-k>`, `<c-k>`.

> Also, you already see flashing up that foo is saved as ###foo$$$.

Yes, that magic sequence is an unavoidable detail. When you hit `<cr>`, [this code](https://github.com/mhinz/vim-grepper/blob/master/autoload/grepper.vim#L599-L603) gets executed. Later the original query is added to the input history: https://github.com/mhinz/vim-grepper/blob/master/autoload/grepper.vim#L540

> No, with <up> everything is fine as it is not remapped. Only <c-k> is.

But when you do `:Grepper<cr>`, `<c-k>`, your mapping is supposed to do `<up><home>`. (As it does in my gif.) When `<up>` is working for you, but not `<c-k>`, it suggests that something else than grepper is the issue here.

**Comment by Konfekt** [comment]
Hmm, perhaps a wrong terminal sequence for `<home>` but the error is the same in gvim.

**Comment by Konfekt** [comment]
The input line history in `.viminfo` is
```
# Input Line History (newest to oldest):
@$$$cr###foo
|2,3,1494416570,,"$$$cr###foo"
@$$$cr###helpful
|2,3,1494415941,,"$$$cr###helpful"
@''
|2,3,1494415930,,"''"
@foo
|2,3,1494415913,,"foo"
@$$$cr###$$$cr###helpful
|2,3,1494347323,,"$$$cr###$$$cr###helpful"
@helpful
|2,3,1494347290,,"helpful"
@help
|2,3,1494322064,,"help"
```
Somehow the magic sequence is not removed.

**Comment by Konfekt** [comment]
The line ` execute 'cnoremap <cr>' s:magic.cr .'<cr>'` seems suspect.

**Comment by Konfekt** [comment]
As you do it,
`:Grepper<cr>, foo<cr>, :Grepper<cr>, bar<cr>, :Grepper<cr>, <c-k>, <c-k>` it is not reproducible. You have to hit `<cr>` instead of `<c-k>` the second time. That is:

`:Grepper<cr>, bar<cr>, :Grepper<cr>, <c-k>, <cr>`.

**Comment by mhinz** [comment]
I get it now. It's because of your `<home>`. Remapping `<cr>` is needed for adding the magic sequence, but the code expects that sequence at the end of the input.

If you do `<c-k>` in the above example, `bar` will appear but your cursor will be in the front. When you now hit `<cr>`, the entry `$$$cr####bar` will be added to the input history.

People and their crazy workflows. :-P Let me see if there's a good way to handle that from grepper.

**Comment by mhinz** [comment]
Please see if the latest commit is working for you.

**Comment by Konfekt** [comment]
Thanks! I found those `<c-j/k>` remappings to combine history and cmd-line completion quite elegant, so  I grew attached to them. Thanks for making Grepper work with 'em!

**Comment by mhinz** [comment]
:+1: And thanks for your quick feedback!
