### ISSUE TITLE
Question about using a scheduler for background search

### ISSUE THREAD

**Issue by Konfekt** [mhinz/vim-grepper#114]
As Grepper supports async, does using a scheduler like 
```vim
chrt --idle 0 ionice -c2 -n7 ag --vimgrep
```
leave Vim more responsive while the background search process is running ?

**Comment by lbonn** [comment]
You can try it by defining custom tools or modifying existing tools' `grepprg`: https://github.com/mhinz/vim-grepper/blob/932a35c741ceaecf19ced87ede9cc8c444e77c23/doc/grepper.txt#L390

As it's probably non-portable, I'd argue it should not be in the defaults.

However, if it brings noticeable improvements for some use cases (long complex regexp search?), it could be documented as an FAQ entry.

Also, if you had some responsiveness issues, IMHO, it' probably more likely that is comes from some vimscript inefficiencies, missing optimizations or vim/neovim limitations. I'd look that way before messing with the system's scheduler :).

**Comment by mhinz** [comment]
I can't comment on this since I'm using macOS, but, for what it's worth, Neovim runs much more fluent with background processes. There's still delay, but it doesn't feel as "blocking" as Vim does.

That's my experience at least. :>

**Comment by mhinz** [comment]
I guess you just have to try it yourself:

```vim
runtime autoload/grepper.vim
let g:grepper.ag.grepprg = 'chrt --idle 0 ionice -c2 -7 ' . g:grepper.ag.grepprg
```

This overrides the default settings for ag.

Other than that, I don't see a way how to improve this behaviour from this plugin. (Try Neovim!)
