### ISSUE TITLE
The Meaning of $$$cr###, the universe and everything

### ISSUE THREAD

**Issue by laktak** [mhinz/vim-grepper#115]
After I run a search I see `$$$cr###` in the command line:

```
ag --vimgrep --follow> test$$$cr###
```

I was just wondering what does it mean?

**Comment by mhinz** [comment]
It's a magic string that indicates that the input was finished using `<cr>`. This is needed to distinguish between empty inputs and cancelled inputs.

We could simply clear the statusline, though.

**Comment by mhinz** [comment]
Well, the question is answered and now that string shouldn't appear anymore, so I'm closing this.

Thanks for bringing this up!

**Comment by laktak** [comment]
> We could simply clear the statusline, though.

Thanks for the plugin and yes, I think that would be less confusing.
