### ISSUE TITLE
Flag to append to the quickfix list

### ISSUE THREAD

**Issue by blueyed** [mhinz/vim-grepper#116]
Currently a new location/quickfix list gets created always.
It would be nice if Grepper could optionally append to an existing one instead.

**Comment by mhinz** [comment]
I added `:Grepper -append`!

**Comment by balta2ar** [comment]
@mhinz It looks like if I use `:GrepperAg -append <query>`, `-append` is not respected... Could you check please?

**Comment by mhinz** [comment]
@balta2ar You can't.

Look at how it is defined with `:com GrepperAg`:

```vim
command! -nargs=+ -complete=file GrepperAg Grepper -noprompt -tool ag -query <args>
```

So, in your case Grepper would run `ag --vimgrep -append <your query>`.
