### ISSUE TITLE
Close the quickfix with <ESC>

### ISSUE THREAD

**Issue by Taverius** [mhinz/vim-grepper#117]
I have muscle memory of this from CtrlP, and even though the tools don't work the same, I still reach for Escape when I want to close it.

Could you add it?

Or can I do it via `autocmd`? If so, can you add that to the wiki? Haven't had any luck figuring it out myself.

**Comment by mhinz** [comment]
The plugin uses either the quickfix (default) or the location window. You can open/close these with `:copen`/`:cclose` and `:lopen`/`:lclose` respectively.

Both set the filetype `qf`, so a general approach could be:

```vim
autocmd FileType qf nnoremap <buffer><silent> <esc> :quit<cr>
```

Does this work for you?

**Comment by Taverius** [comment]
Not sure how I missed the qf filetype, but you learn something new every day with Vim!

Added this to my vimrc:

```viml
augroup vimrcQfClose
    autocmd!
    autocmd FileType qf if mapcheck('<esc>', 'n') ==# '' | nnoremap <buffer><silent> <esc> :cclose<bar>lclose<CR> | endif
augroup END
```

Works perfectly.

**Comment by mhinz** [comment]
> [...] but you learn something new every day with Vim!

Yes, unfortunately that never ends. :-)

Glad you found a solution that works for you!
