### ISSUE TITLE
Vim grepper displaying "No such tool: Rg" when I use "GrepperRg"

### ISSUE THREAD

**Issue by tyrocca** [mhinz/vim-grepper#118]
First I want to say thank you for a great plugin! I just updated it today and the "GrepperRg" command no longer works. I am using neovim 2.0 on a mac

**Comment by tyrocca** [comment]
The same issue happens for GrepperAg - think it might be something with this commit 30cb75f

**Comment by mhinz** [comment]
When you start nvim, what's the output of `:echo g:grepper.tools`?

**Comment by mhinz** [comment]
Oh, my bad. It should work now!

**Comment by tyrocca** [comment]
Thank solved it! Thank you!
