### ISSUE TITLE
coffeescript search problem in neovim

### ISSUE THREAD

**Issue by vbauerster** [mhinz/vim-grepper#12]
In Neovim while current buffer file type is coffee, any search attempt results 0 matches.
In Vim it is ok.
I use kchmck/vim-coffee-script plugin for coffeescript

**Comment by mhinz** [comment]
And that only happens when `ft=coffee`? What tool do you use for searching?

**Comment by mhinz** [comment]
I can't reproduce it in any way. Please reopen if this is still the case.

**Comment by vbauerster** [comment]
Sorry for late response, but looks like this issue is not relevant any more.
I confirm search works with both ag and git tools, in Neovim v0.1.0

**Comment by mhinz** [comment]
Glad it's working now. Thanks for feedback!
