### ISSUE TITLE
Async in Neovim, not async in Vim

### ISSUE THREAD

**Issue by gabebw** [mhinz/vim-grepper#121]
Hi! This is a really cool project that will hopefully solve my number one complaint about Vim 😄 

In regular Vim: When I run `:GrepperAg User` in a (reasonably large) project, it hangs for about 6 seconds and then shows the quickfix window. I can't move around or do anything else while it searches.

In Neovim: I can edit files and move around while grepping.

------------------------

#### Vim

`vim --version` (hidden inside a `<details>` block so it's not huge):

<details>
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jun 24 2017 12:45:56)
MacOS X (unix) version
Included patches: 1-666
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl             +file_in_path    +mouse_sgr       +tag_old_static
+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           +mouse_urxvt     -tcl
-balloon_eval    +folding         +mouse_xterm     +termguicolors
-browse          -footer          +multi_byte      +terminfo
++builtin_terms  +fork()          +multi_lang      +termresponse
+byte_offset     -gettext         -mzscheme        +textobjects
+channel         -hangul_input    +netbeans_intg   +timers
+cindent         +iconv           +num64           +title
-clientserver    +insert_expand   +packages        -toolbar
+clipboard       +job             +path_extra      +user_commands
+cmdline_compl   +jumplist        +perl            +vertsplit
+cmdline_hist    +keymap          +persistent_undo +virtualedit
+cmdline_info    +lambda          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       +python          +vreplace
+cscope          +lispindent      -python3         +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con      -lua             +rightleft       +writebackup
+diff            +menu            +ruby            -X11
+digraphs        +mksession       +scrollbind      -xfontset
-dnd             +modify_fname    +signs           -xim
-ebcdic          +mouse           +smartindent     -xpm
+emacs_tags      -mouseshape      +startuptime     -xsmp
+eval            +mouse_dec       +statusline      -xterm_clipboard
+ex_extra        -mouse_gpm       -sun_workshop    -xterm_save
+extra_search    -mouse_jsbterm   +syntax          
+farsi           +mouse_netterm   +tag_binary      
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X_UNIX  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: clang   -L. -fstack-protector -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o vim        -lncurses -liconv -framework Cocoa   -mmacosx-version-min=10.12 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.26.0/lib/perl5/5.26.0/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc -F/usr/local/opt/python/Frameworks -framework Python   -lruby.2.4.1 -lobjc    
</details>

`~/.vimrc`:

```vim
set nocompatible

call plug#begin('~/.vim/bundle')
Plug 'mhinz/vim-grepper'
call plug#end()

filetype plugin indent on
syntax enable
silent! colorscheme l80snight
```

#### Neovim

Contents of `~/.config/nvim/init.vim`:

```vim
set runtimepath^=~/.vim runtimepath+=~/.vim/after
let &packpath = &runtimepath
source ~/.vimrc
```

Thanks!

**Comment by mhinz** [comment]
Unfortunately I guess that's just how Vim works.

The stdout handler, which handles the output of ag, has to do a lot of things. Now, the difference between Vim and Neovim is that Vim calls the stdout handler for _each_ single line whereas Neovim batches multiple lines as a single input to the stdout handler. The latter works much better when ag outputs lots of text.

Just to be sure that it really uses the async version, could you try another long-running search?
E.g. `:cd | Grepper -tool grep -query abcdef`? This should run for multiple seconds not yielding too many matches. Can you move the cursor in the meanwhile?

(You can stop a running search via `:Grepper -stop`.)

**Comment by gabebw** [comment]
Weird, `:cd | Grepper -tool grep -query abcdef` does run for a while (as do queries for e.g. `a`) but I can edit while doing it. `:cd | GrepperAg abcdef` works fine, too. (Though after a while it does slow down my whole computer...)

Anyway, thanks!

**Comment by mhinz** [comment]
Maybe someone can convince Bram to switch to a battle-tested library like [libuv](https://github.com/libuv/libuv), like Neovim does, instead of using an unoptimized custom solution. :-)

Thanks for bringing this up anyway!
