### ISSUE TITLE
-buffer and -buffers flags broken on Windows

### ISSUE THREAD

**Issue by cheathcott** [mhinz/vim-grepper#124]
Both -buffer and -buffers seem to be broken whenever a buffer name contains a backslash (because the file resides in a different directory than the present working directory). I'm guessing that the backslashes in the buffer names need to be escaped.

To test this I created a folder "C:\a", and I created two files therein, "C:\a\b.txt" and "C:\a\c.txt". The contents of both files is the single line "123".

I opened Vim, and changed directory to "C:\a", and I loaded both files into separate buffers, and the output of `:buffers` is:

```
1  #h  "b.txt" line 1
2  #%a "c.txt" line 1
```

Then, I ran `:Grepper -tool ag -cword -noprompt -buffers`, and the output is

```
b.txt|1 col 1| 123^M
c.txt|1 col 1| 123^M
```

And I see the command was translated to `ag --vimgrep -- "\b123\b" "b.txt" "c.txt"`

So far, so good.

However, this same command fails when I opened Vim, and I changed directory to "C:\" and I again loaded the files into separate buffers such that the output of `:buffers` is:

 ```
1  #h  "a\b.txt" line 1
2  #%a "a\c.txt" line 1
```

Now, the output of `:Grepper -tool ag -cword -noprompt -buffers` is:

```
|| ERR: Error opening directory a^H.txt: No such file or directory
|| ERR: Error opening directory ac.txt: No such file or directory
```

And I see the command was translated to `ag --vimgrep -- "\b123\b" "a^H.txt" "ac.txt"`

Again, it appears that the backslashes in the buffer names were not properly escaped.

Here's my environment:

Windows 10 Enterprise 15063.483
vim 8.0.0737
ag 0.29.1.1641
vim-grepper 1.4 (via vim-plug)

Let me know if there is anything else I can provide that would help debug. Cheers.

**Comment by mhinz** [comment]
Thanks to your good description I can reproduce it just fine in a VirtualBox VM.

I'll look into it!

**Comment by mhinz** [comment]
Please pull the latest commit and see if it's working now!

**Comment by cheathcott** [comment]
Yes! Backslash escaping in buffer names is working properly now. Thank you for the prompt resolution and for sharing this great plugin with the world!

**Comment by mhinz** [comment]
Thank you for using it and actually reporting issues I'd never catch otherwise. :-)
