### ISSUE TITLE
Manual folds lost after using grepper

### ISSUE THREAD

**Issue by Jeansen** [mhinz/vim-grepper#126]
Using grepper (default with ag) results in a lost of my custom folds if foldmethod is set to manual. I am not sure, what is best provided to help with this issue, so just let me know, please :)

**Comment by mhinz** [comment]
Usually manual folds only get removed, when a buffer gets abandoned. E.g. just `:edit` "reloads" the current file and removes the folds.

But when you search something with grepper, the quickfix list will be filled with a list of lines and their files. Then you open an entry with `<cr>`. That either opens a new buffer or switches to one if it was already loaded in Vim.

What are the exact steps you take?

**Comment by Jeansen** [comment]
No, it was a bug in vim https://github.com/vim/vim/issues/1958

**Comment by mhinz** [comment]
Ah, okay. Thanks for letting me know.
