### ISSUE TITLE
Shell escape query(?)

### ISSUE THREAD

**Issue by SevereOverfl0w** [mhinz/vim-grepper#130]
This only happens when doing it via the prompt, not when doing it via `-query '(defn'`.

I tried to query for `(defn` which didn't work.

Quickfix was opened with:
`|| sh: 1: Syntax error: "(" unexpected`

I understand this might not be desirable, I guess, but it would be for me.

**Comment by mhinz** [comment]
This is done on purpose. You always have to think of the prompt as a pre-populated shell command-line.

The git prompt defaults to `git grep -nI`, so `-i 'foo bar' *.vim` is a perfectly valid query. It's easy to see that implicitly putting quotes around that would lead to mayhem.

But I'm okay with introducing a new opt-in option, that puts a custom quote around the input. So people can choose whether they prefer single or double quotes.

How does this sound?

**Comment by SevereOverfl0w** [comment]
Rather than focus on quotes, would toggling `shellescape()` be the appropriate behaviour for the option?

**Comment by mhinz** [comment]
> Rather than focus on quotes, would toggling shellescape() be the appropriate behaviour for the option?

:+1:

`g:grepper.prompt` already exists, so let's call it `g:grepper.prompt_quoting`?

**Comment by mhinz** [comment]
Okay, should work now. Please update and put this in your vimrc:

```vim
let g:grepper = {}
" ...
let g:grepper.prompt_quote = 1
```

Thanks for your feedback!
