### ISSUE TITLE
:help grepper returns "Sorry, no help for grepper"

### ISSUE THREAD

**Issue by tjharman** [mhinz/vim-grepper#131]
Am I an idiot? (Hint: I probably am)
But :help grepper doesn't return anything. (Sorry, no help for grepper)
I can't find anything in :help that matches grepper either?

I note there is no tags file in doc, does that matter?

I am using vim-plug, I've tried on both my windows and linux boxes.  I've tried running:
:call plug#helptags()

But that didn't work either.

On a scale of 1-10, how dumb am I? :)

**Comment by mhinz** [comment]
You probably use Plug's lazy loading. Some like..

```
Plug 'mhinz/vim-grepper', { 'on': 'Grepper' }
```

That way, the documentation won't be found, unless `:Grepper` was used at least once.

**Comment by tjharman** [comment]
I certainly am and you're right, soon as I use it, it works.
Sorry for wasting your time.

**Comment by mhinz** [comment]
No worries, I've got bitten by that multiple times already. :-)
