### ISSUE TITLE
GrepperOperator and -cword flag require an extra <CR>.

### ISSUE THREAD

**Issue by tandrewnichols** [mhinz/vim-grepper#132]
I have `gr` mapped to GrepperOperator, so I would expect `griw` to grep for the word under cursor, but it just pulls up the Grepper command completion like: `ag --vimgrep> -- 'word'` and I have to hit enter again. Similarly, if I type `:Grepper -cword` and hit enter, I get `ag --vimgrep> -- 'word'` and have to enter again. It seems like that should just go ahead and _do_ the search. It's also impossible to map around this because you end up with an error that says -cword^M is not a valid option.

**Comment by mhinz** [comment]
Yup, that's my preferred behaviour and described like that under `:h grepper-operator`.

1. For the `:Grepper -cword` example you'll need to use `:Grepper -noprompt -cword` instead.
1. Alternatively, you can tell Grepper to never prompt by default via `let g:grepper.prompt = 0`. Then, if you have `:Grepper` mapped, you consequently should use `:Grepper -prompt` instead.

Does this work for you?

**Comment by tandrewnichols** [comment]
Yes, although it seems like that should be the default.

**Comment by mhinz** [comment]
Okay, I changed it to not prompt by default. Let's see how it works out.

One problem I see is having git as default tool and then using the operator outside of a git repo. I'll probably change the plugin to fall back to the next tool in that case.

Thanks for the feedback!

**Comment by tandrewnichols** [comment]
Wow, cool. I sort of thought you might lament that it wasn't practical to make that change for backward compatibility reasons or something. Cheers!

**Comment by kawas44** [comment]
Hi,

May I suggest a configuration option for this behavior ?
g:grepper.operator_use_prompt=1  (default value)

IMO, previous behavior with a prompt had three advantages :
- consistency in grepper usage experience
- allow to verify/update word to match
- allow to update tool's options (ex. some time you know you want fix string match here)

Cheers

By the way, thank you for your awesome work on this plugin. It help to keep them grep tools packed and clean 😉

**Comment by mhinz** [comment]
Let's fix this all at once by introducing a new kind of namespace `g:grepper.operator` which takes exactly the same options than `g:grepper`. This way we can configure the normal and operator behaviour on their own.

For this case, people could then use:

```vim
let g:grepper = {}
let g:grepper.prompt = 1
let g:grepper.operator.prompt = 0
```

The above will also be the default, because I agree with @tandrewnichols that not showing a prompt when using the operator is more Vim-like.

**Comment by kawas44** [comment]
Great news, to have a configuration for that.

Just on the user perspective, it appears that you have now to duplicate your configuration in the operator namespace event if your have one config value to change.

What do you think of merging operator dict over root dict in [operator code](https://github.com/mhinz/vim-grepper/blob/e77431179414cd9e34687b4086ea90b5f85432c5/plugin/grepper.vim#L1008), so that root configuration act as default ?

Anyway I am very happy with the current operator namespace.

Cheers

**Comment by mhinz** [comment]
Actually.. that's surprisingly hard to get right considering the use of `runtime plugin/grepper.vim` in the vimrc which populates `g:grepper` with all default values already.

A patch will come soon.

**Comment by mhinz** [comment]
@kawas44 

It _should_ work now, but it was a rather complex change and it would be nice to get confirmation!

**Comment by kawas44** [comment]
Hi I made some tests on latest master,

- Without g.operator.prompt and prompt_quote, everything works fine [ok]
- With g.operator.prompt there are some extra dashes in front of the word that are used quoted in the search query [KO]
- With g.prompt_quote, when I switch tools I get extra quote-dollar in quotes to insert my word

Here is my grepper configuration, my test is to open a file in current dir and then try to find a word in files above in a git repo 
```vim
" grepper
runtime plugin/grepper.vim
let g:grepper.tools = ['rg', 'git', 'grep']
let g:grepper.dir = 'repo,filecwd'
let g:grepper.prompt_quote = 3
let g:grepper.operator.prompt = 1

nnoremap <leader>g :Grepper<cr>
nmap gr <plug>(GrepperOperator)
xmap gr <plug>(GrepperOperator)
```

I think there is a weird interaction between options or/and an other plugin (tab usage to switch tools...)
Do you have any bugs like thoses ?

**Comment by mhinz** [comment]
Okay, I can confirm both bugs. Will look into it later today.

**Comment by kawas44** [comment]
@mhinz everything is find now !
Thanks for this feature of options merge, not so easy indeed :)
