### ISSUE TITLE
Can I open the file right way after searching

### ISSUE THREAD

**Issue by ztlevi** [mhinz/vim-grepper#135]
After searching, the results are only shown as a buffer. 

I am wondering if there is a way to go to that specific result.

Thanks.

**Comment by mhinz** [comment]
That buffer is not a regular buffer, but the "quickfix" buffer.

See https://github.com/mhinz/vim-galore#quickfix-and-location-lists on how to open or navigate the entries from the quickfix buffer.

**Comment by ztlevi** [comment]
Got you. 

Damn it. My vim tweaks the <Enter> and I finally figure out I should use `:.cc` to navigate to the location.

Thanks!
