### ISSUE TITLE
Make hitting Backspace after entering the prompt delete both quotes if prompt_quote > 1

### ISSUE THREAD

**Issue by Konfekt** [mhinz/vim-grepper#138]
As a sequel to https://github.com/mhinz/vim-grepper/issues/136, if `g:grepper.prompt_quote = 2` or `3`, then make `<BS>` delete both quotes (also the closing one) if hit immediately after entering the prompt.

**Comment by mhinz** [comment]
Isn't this becoming a tad too magical now? :-P

How about a fancy user mapping like this?

```vim
:cnoremap <expr> <bs> (getcmdline() =~ '[''"]\{2}') ? '<end><c-u>' : '<bs>'
```

So, when the command-line consists only of `''` or `""` (or `'"` or `"'`), no matter where the cursor is, empty the line. Use normal `<bs>` otherwise. This works for prompts as well.

**Comment by Konfekt** [comment]
Ok, I am quite fine with this solution.

**Comment by Konfekt** [comment]
Perhaps this is a good alternative, similar to what `DelimitMate` does:
```vim
function! <SID>BetweenQuotes()
  let pos = getcmdpos()
  let curLeftRight = getcmdline()[pos-2:pos-1]
  return  curLeftRight is# '""' || curLeftRight is# "''"
endfunction

cnoremap <expr> <BS>  <SID>BetweenQuotes() ? '<Del><BS>' : '<BS>'
cmap            <C-H> <BS>
```
