### ISSUE TITLE
[Question] How to search using visual selection in current buffer only?

### ISSUE THREAD

**Issue by Asheq** [mhinz/vim-grepper#139]
The visual mode map below searches from `cwd` by default.

    xmap gs <plug>(GrepperOperator)

What is the preferred way to setup a map that does the same thing but only in the current buffer?

Thanks!

**Comment by mhinz** [comment]
With the latest version you can set all available options for the operator as well.

Usually `g:grepper.buffer = 1` would limit the search to the current buffer, so in this case you want:

```vim
runtime plugin/grepper.vim " initialize g:grepper
let g:grepper.operator.buffer = 1
```

But.. this alone _could_ lead to an issue where you have a double-dash in your command-line _twice_. One coming from using the operator, and one from using the `buffer` option. It doesn't happen with all tools, though.

If it happens, you can specify the cmd to be used like this:

```vim
let g:grepper.operator.ag.grepprgbuf = 'ag --vimgrep $* $.'
```

Here `$*` will be replaced by the query (prepended with a `--` already) and `$.` the file of the current buffer.

Hope this helps!

**Comment by Asheq** [comment]
Seems like you thought through everything with this plugin! Love it.

**Comment by hanyk** [comment]
How to define two maps:
 one with let g:grepper.operator.buffer = 1, 
another with let g:grepper.operator.buffers = 1?

**Comment by mhinz** [comment]
@hanyk 

There is no way to provide options to an operator and the plugin can't provide plug mappings for all combinations of options. You have to define the operator mapping yourself and set (and reset!) the options in that same mapping.

With the latest version of the plugin (I just exposed `GrepperOperator()`), you can do this:

```vim
nnoremap gs :let [g:grepper.operator.buffer, g:grepper.operator.buffers] = [1, 0]<cr>:set opfunc=GrepperOperator<cr>g@
xnoremap gs :let [g:grepper.operator.buffer, g:grepper.operator.buffers] = [1, 0]<bar><c-u>call GrepperOperator(visualmode())<cr>

nnoremap gl :let g:grepper.operator.buffers = 1<cr>:set opfunc=GrepperOperator<cr>g@
xnoremap gl :let g:grepper.operator.buffers = 1<bar><c-u>call GrepperOperator(visualmode())<cr>
```

Ugly, but gets the job done. (`buffers` takes precedence over `buffer`, so the gs mapping has to reset it.)

**Comment by hanyk** [comment]
@mhinz 
Thanks a lot for your reply! However, I got this:
"E117: Unknown function: GrepperOperator".

**Comment by hanyk** [comment]
@mhinz 
Wow, after "PlugUpdate", everything works great!
