### ISSUE TITLE
s key gets overwritten by vim-grepper

### ISSUE THREAD

**Issue by vbauerster** [mhinz/vim-grepper#14]
I've following configuration:
```
  command! -nargs=* -complete=file GG Grepper! -tool git -open -switch -query <args>
  command! -nargs=* -complete=file Ag Grepper! -tool ag -open -switch -query <args>
  nnoremap <Leader>* :<C-u>execute "GG " . expand("<cword>") <Bar> cw<CR>
  nnoremap <Leader>gs :Grepper! -tool git -open -switch<CR> " mnemonic is git search
  nnoremap <Leader>ag :Grepper! -tool ag -open -switch<CR>
```
After I use ```<Leader>*``` command, s key gets overwritten.
Here is the [output](https://drive.google.com/file/d/0ByRz5v9LmStMdzU3bUtETksyeDQ/view) of ```:verbose nmap s```
pressing s in normal mode, [tries to make new buffer](https://drive.google.com/file/d/0ByRz5v9LmStMckRlSEFYTnItRk0/view), from word under the cursor

**Comment by vbauerster** [comment]
First I thought, that problem could be in asterisk in```<Leader>*``` and it should be escaped in some way. Therefore I've changed the mapping to different key, but this didn't help - same problem persist.

**Comment by mhinz** [comment]
Oh, wow. Let me look into it.

**Comment by mhinz** [comment]
@vbauerster It should work now. Quite embarassing bug, though..

**Comment by mhinz** [comment]
BTW, you can now replace the above mapping like this:
```vim
nnoremap <leader>* :Grepper! -tool git -open -switch -cword
```
