### ISSUE TITLE
Honor git submodules when using g:grepper.dir = 'repo'

### ISSUE THREAD

**Issue by geneotech** [mhinz/vim-grepper#140]
If I perform ``Grepper -tool git`` while being in a submodule, the result list is always empty.

That is because submodules do not create a ``.git`` directory; on the other hand, ``s:compute_working_directory`` looks exactly for a ``.git`` directory to determine where to launch the ``git grep`` command - and it always finds the topmost, parent repository.

Unfortunately, ``git grep`` does not search through submodules by default - you have to use ``--recurse-submodules`` flag. Currently, if I launch grepper while browsing the submodule files, they are completely omitted from search.

I propose two things:
- Let grepper.git.grepprg use ``--recurse-submodules`` by default.
- Even better, I suggest that ``s.compute_working_directory`` does something like this:

            " This hack actually works for me
            
            if dir == 'repo'
              return system("pushd " . expand('%:p:h') . "; git rev-parse --show-toplevel")

  Which will additionally always limit the search to the current submodule - we could introduce another option for this, named "git_repo". Note that, if we just provide grepprg with ``--recurse-submodules`` instead, we always search through the entire repository along with other, unrelated submodules. 

Last but not least, thank you for an amazing plugin!

**Comment by mhinz** [comment]
Okay, it now tries `git -C <current dir> rev-parse --show-toplevel` before looking though `g:grepper.repo`.

Thanks for the suggestion!

**Comment by geneotech** [comment]
Awesome! Works just as intended 👍
