### ISSUE TITLE
'-cword' not working on windows gvim

### ISSUE THREAD

**Issue by fftyjw** [mhinz/vim-grepper#141]
When use '-cword'  flag on windows gvim, the word under cursor was automatic enclosed by "\b and \b", but  the "ag" tool  treated all these " and \b characters as the word to search, so the result is "no matches found".  I can add empty wordanchors to "ag" tool use configuration "g:grepper" to avoid automatic enclose by \b character， but I cannot get rid of  the double quotation marks without modify the source code. I don't think I'm the only one who meets this problem, so please consider to fix this ,thank you.

**Comment by mhinz** [comment]
Sorry, but I don't have a Win environment and I rely on external patches for Windows support.

Enclosing the word with `\b` and quotes is the usually the correct way when using `-cword`, so I suspect that it's the way we run the command on Windows.

I'm looking at https://github.com/mhinz/vim-grepper/blob/df33f2bb8af0d03ec8358e6aab80866c8d9fdab9/plugin/grepper.vim#L718-L725 right now.

What the output of `:echo &shell`?

**Comment by fftyjw** [comment]
the output is: c:\windows\system32\cmd.exe

**Comment by mhinz** [comment]
Okay, I set a VM now but I can't really reproduce it.

1. Which Vim version do you use? I use the latest installer from vim.org, which is Vim 8.0.586.
2. For some reason `'shell'` is not set to an absolute path for me but only `cmd.exe`. But even when I changed it to `c:\windows\system32\cmd.exe` is kept working.
3. When you get double quotes (opposed to single quotes), it probably means that `:echo &shellslash` is `0` for you. And it should be `0`.
4. Do you use Windows 10 and the latest version of this plugin?

**Comment by fftyjw** [comment]
1:My vim version is: 8.0.445
3::echo &shellslash is 0
4:I use windows 10
5:I do not think the problem is related to wrong search directory, because when used with -buffer flag, I still got the same result.

**Comment by mhinz** [comment]
(You didn't mention it earlier, but I assume you're using the latest version of the plugin.)

Hmm. Not sure what else could be different in our environments.

Do you set `g:grepper` in your vimrc? Maybe it's an unfortunate combination of options.

**Comment by fftyjw** [comment]
hi mhinz, I reverted my changes to grepper source code to recreate the problem, but the problem was gone. I think it's the vimrc that caused the problem before. Anyway, now my grepper is working fine, thanks for your patient and have a nice day.

**Comment by mhinz** [comment]
Ah, okay. I can finally reproduce it with `-buffer`. I'll look into a fix!

**Comment by mhinz** [comment]
Please update the plugin and see if the error still occurs.

**Comment by fftyjw** [comment]
I update the plugin and there is an error when search in buffer:
|| ERR: Error opening directory main.lua: No such file or directory

My config:
nnoremap * :Grepper -tool ag -cword -noprompt -buffer<cr>

**Comment by mhinz** [comment]
What is your `:pwd` at that time? Are you in a repo? Please describe it a bit more.

**Comment by mhinz** [comment]
Okay, please update again. It _should_ work now. ;-)

**Comment by fftyjw** [comment]
Hi mhinz, I updated the plugin, now the error is gone. But the -noprompt flag is not working.

**Comment by mhinz** [comment]
What is happening instead? Do you get the `No matches found` message? When you do `:lopen` after using `:Grepper` you open the location list window. Its statusline should show the exact command that was run. What is it?

**Comment by fftyjw** [comment]
Sorry, my bad, I confuse the -noprompt flag with the -noopen flag.

**Comment by mhinz** [comment]
:-) So, everything is working as expected now?

**Comment by fftyjw** [comment]
Yes, everything is ok.
