### ISSUE TITLE
Windows: -buffers works as -buffer

### ISSUE THREAD

**Issue by Lukas3** [mhinz/vim-grepper#144]
The option -buffers works as -buffer. 
in SO Win7-64 ; Vim 8.0

2018-01-28 Edit: The issue is only produced if the args>=2 (gvim file1 file2) and it's not charging more files (buffers) after .

**Comment by mhinz** [comment]
Thanks, I'll look into it.

**Comment by mhinz** [comment]
I reworked the Windows support quite a bit.

I could reproduce your problem on a Win 10 VM, but the latest commits fixed it for me.

Can you confirm that?

**Comment by Lukas3** [comment]
Solved
Good work 
Thanks !!!

**Comment by mhinz** [comment]
Awesome! Thanks for bringing this up. ✨
