### ISSUE TITLE
E182: Invalid command name due to ack-grep

### ISSUE THREAD

**Issue by arecarn** [mhinz/vim-grepper#148]
I'm getting the following error when vim-grepper is being loaded.
```
Error detected while processing /evtfs/home/rcarney/.cache/vim/plugins/bundle/.cache/vimrc_test/.dein/plugin/grepper.vim:
line 1089:
E182: Invalid command name
Press ENTER or type command to continue
```

This is due to your recent change in c593164fdaf88acce3458e7d738f890dc51e1bee that adds ack-grep as a tool, and you are trying to create the command "GrepperAck-grep" at plugin/grepper.vim:1089  but dashes '-' are not allowed in command names resulting in the "E182: Invalid command name" error.

Maybe you can remove dashed before creating the command. e.g.
`let s:utool = substitute(s:utool, '-', '', 'g')`

**Comment by mhinz** [comment]
Thank you! ✨

**Comment by arecarn** [comment]
Thank you! No more error 👍
