### ISSUE TITLE
Use cword by default for empty input

### ISSUE THREAD

**Issue by blueyed** [mhinz/vim-grepper#15]
Thanks for this plugin!  I was using https://github.com/ervandew/ag before.

I think it would be nice to automatically use `<cword>` when no input for a search term was provided.

I have the following mapping and would like to just press Enter again to use `<cword>` (the word under the cursor):

    n  ,a          * :Grepper -tool ag -noopen -noswitch<CR>

The workaround (which is sensible) is to use `<ctrl-r><ctrl-w>`, but an empty input could be handled in the same way?!

**Comment by mhinz** [comment]
> Thanks for this plugin!

You're welcome. :-)

Actually I'd like to keep the behaviour that a simple `:Grepper` opens the prompt, but I could add a new flag `-cword`. This should work just as well for your use case, right?

**Comment by blueyed** [comment]
Sorry for the misunderstanding: `:Grepper` should still open the prompt, but when you then submit nothing from there, `<cword>` would be used, i.e. with `:Grepper<cr><cr>`.

**Comment by mhinz** [comment]
In that case you could use the operator:
```vim
nmap gs <plug>(GrepperOperator)
xmap gs <plug>(GrepperOperator)
nmap <leader>a gsiw
```
The only downside I see, is that using this way always the first tool in `g:grepper.programs` will be used. So you couldn't create 2 mappings for git and ag it.

Alternatively, and maybe more straight forward, would be `-cword` (prompt) and `-cword!` (no prompt).

What do you think?

**Comment by blueyed** [comment]
I am aware of the operator already, which is nice in general.

Do you mean that with `-cword` it would display a prompt, prefilled with the current word, and that `-cword!` would just use the current word?

The use case of having an empty prompt being submitted would still not be covered in this regard then, right?

**Comment by mhinz** [comment]
Oh, apparently I'm a bit schwer von Begriff today. Give me a minute..

**Comment by blueyed** [comment]
Bingo, thanks! :)

**Comment by blueyed** [comment]
..nice to have a set of new features as a by-product.. ;)

**Comment by mhinz** [comment]
> ..nice to have a set of new features as a by-product.. ;)

Indeed.

Thanks for the feedback!
