### ISSUE TITLE
Support on-the-fly (incremental) search while keeping the prompt open

### ISSUE THREAD

**Issue by MaskRay** [mhinz/vim-grepper#150]
Invoke the search tool whenever the user changes the pattern in the prompt.

**Comment by mhinz** [comment]
I can't think of any way to get Vim to fetch characters from the command-line while they're typed, so unfortunately this is not possible.

Sorry!

**Comment by MaskRay** [comment]
I see, probably the limitation of Vim UI

**Comment by mhinz** [comment]
Okay, there might be a way using timers and `getcmdline()` and friends, but this plugin simply wasn't designed for that. And it probably wouldn't be very performant to run the tool and discard all prior matches on each key press.

Somehow reusing fzf would be better in this case.
