### ISSUE TITLE
Open results in new tabs?

### ISSUE THREAD

**Issue by p0l1cy** [mhinz/vim-grepper#155]
Is there a way to open the results in a new tab? That'd be really helpful :clap: Thanks for the awesome plugin!

**Comment by mhinz** [comment]
Thanks!

I guess you mean opening an entry from the quickfix window in a new tab? For these cases there are dedicated plugins: https://github.com/mhinz/vim-grepper/blob/master/doc/grepper.txt#L414-L419

Grepper sported a few custom mappings in the past, but I removed them in favor of these plugins. No use to duplicate code. :)

**Comment by mhinz** [comment]
BTW, here a custom mapping that you could use:

```vim
autocmd FileType qf nnoremap <buffer><silent> t :execute 'tabedit' matchstr(getline('.'), '^.\{-}\ze\|')<cr>
```

Now, in every quickfix buffer, you can simply use `t` to open the current entry in a new tab.

**Comment by mhinz** [comment]
Actually.. thinking about that.. I might add a few mappings to the plugin but also add an option to disable them, in case they're interferring with above mentioned plugins or the user's custom mappings.

**Comment by p0l1cy** [comment]
Thanks! Turns out, QFEnter is just what I needed :smile: I personally think if this information was in the main README that'd be enough.
