### ISSUE TITLE
pass along args to tool ?

### ISSUE THREAD

**Issue by mellery451** [mhinz/vim-grepper#16]
awesome plugin!

Probably user error -- but I can't figure out how to specify args that are passed directly to the tool. For instance, with ag, I'd like to have a mapping that searches only .txt files:

    nnoremap <leader>st  :Grepper! -tool ag -cword! -G"^.+\.txt$" <cr>

..where the -G argument is passed directly to ag. The thing above doesn't seem to work - is there a way to specify tool specific options like this?

**Comment by mhinz** [comment]
> awesome plugin!
Thanks!

**Already working:**
The way it was supposed to bet set so far, is like this:
```viml
let g:grepper = {}
let g:grepper.ag = { 'grepprg': 'ag --vimgrep -G "^.+\.txt$" $* ' }
```
Although this wasn't quite working at the time you opened this issue. But it does now! (You can leave out the `--vimgrep`, but then the output won't contain the column.)

**About to be added:**
This, of course, would hardcode it for all invocations of `:Grepper -tool ag`. You can't specify arguments on the command-line yet, but I guess I could add a new flag `-args`.

I imagine it looking like this:
```viml
nnoremap <leader>ag :Grepper! -tool ag
nnoremap <leader>at :Grepper! -tool ag -cword! -args '-G "^.+\.txt$"'
```
I see what I can do.

**Comment by mellery451** [comment]
Thanks for the info. I like the -args idea - that would work well for me

**Comment by mhinz** [comment]
I won't have time until Sunday afternoon, but here's a sneak preview: `git pull && git checkout add-grepprg-flag`.

Due to technical reasons, one has to specify the whole command. In that branch this works:
```viml
Grepper! -tool ag -grepprg ag --vimgrep -G \"^.+\.txt\"
```

**Comment by mhinz** [comment]
Okay, it's merged now.

**Comment by mellery451** [comment]
works great - thanks!

**Comment by mhinz** [comment]
Awesome, thanks for the feedback!
