### ISSUE TITLE
Save query history with -noprompt

### ISSUE THREAD

**Issue by blueyed** [mhinz/vim-grepper#161]
I have a wrapper command to call `Grepper -noprompt -tool rg -jump -noopen -query <args>`.
When using this the query (via `<args>`) is not being saved to the history.
I have not checked the source, but it looks like using `-noprompt` causes it to not be saved.

Maybe an extra option (`-savequery`) could be used if this is not desirable to have by default.

**Comment by mhinz** [comment]
Thanks! ✨

**Comment by blueyed** [comment]
Awesome, thanks!
