### ISSUE TITLE
grep: only use "." by default

### ISSUE THREAD

**Issue by blueyed** [mhinz/vim-grepper#162]
grep.grepprg is defined as `'grep -RIn $* .'`, which causes `-query foo dir` to be run as `grep .. foo dir .`, while you would expect it to be `grep … foo dir` only (without the dot).

To fix this something like "default dir" could be added, which only gets used if there is a single arg (query) only.

So "." would be used with "-query foo" and "-query 'foo bar'", but not "-query foo bar".

I am working on a fix for vim_query (with -highlight) to extract the query part correctly, which could be used here then, too.  See https://github.com/mhinz/vim-grepper/pull/163.

**Comment by mhinz** [comment]
The design of this plugin is very simple. It pre-populates the command-line and lets the user append the rest:

```
:Grepper -tool git -query -i foo dir | head -n3
```

I just don't see a reliable way to detect whether a path is given already or not. Same is true for getting the actual query for highlighting.

**Comment by blueyed** [comment]
I've understood `-query …` to be used as a query, and that this part could be parsed into query and path, but forgot about options in there.

Given 4ad3de5 has been merged maybe we could assume `[options] [query] [dir…]'?
Although "options" really could be taken out of it in the beginning (before any `--`), and `query` should be a single argument (which includes `"foo bar"`).

**Comment by mhinz** [comment]
Hmm, this is all... suboptimal. ;-)

I mean, parsing something like `--foo -x "option value" -b 'my "--query"' file1 dir/* -x` would be hell. And making it work on Windows with its different rules to parsing quotes depending on which shell is used doesn't make it easier.

So, I'm closing this and the related PRs. Harsh decision, I know. But currently I focus on other things and try to avoid adding new features or things that need a lot of paying attentions to details and ongoing maintenance in the future.

This plugin works great for my use cases but probably horribly for people expecting other use cases. It's not well designed and adding new things is a pain.

Hope you understand!

**Comment by blueyed** [comment]
Just for reference: Python's shlex could be used (and possibly ported to VimL, of course):
```python
import shlex
shlex.split('--foo -x "option value" -b \'my "--query"\' file1 dir/* -x')
['--foo', '-x', 'option value', '-b', 'my "--query"', 'file1', 'dir/*', '-x']
```

**Comment by mhinz** [comment]
Okay, I guess writing a function `s:shlex()` wouldn't be too hard, but the main problem is still _finding_ the query.

Imagine `-x foo bar`. This could mean two things:

1. Boolean option `-x`, query `foo`, path `bar`
1. Option `-x` with argument `foo`, query `bar`
