### ISSUE TITLE
Should escape & by default

### ISSUE THREAD

**Issue by blueyed** [mhinz/vim-grepper#166]
Using `foo\ &bar` for the query might run `['sh', '-c', 'rg -H --no-heading --vimgrep --sort-files foo\ &bar']`, which then results in an extra entry:

> || sh: bar: command not found

The `&` gets interpreted by the shell to run everything before it in the background.

(It looks like it gets done when substituting `$*` (https://github.com/mhinz/vim-grepper/blob/04d659c9e0a57e0c3e989069601d2a98df0386c4/plugin/grepper.vim#L712), but that is only to escape it for `substitute` after all.)

btw: this is only necessary because of wrapping the cmd in a shell, which could be avoided maybe, even when keeping `grepprg` as a string by using Python's `shlex.split`:
```diff
diff --git i/plugin/grepper.vim w/plugin/grepper.vim
index ed3e20d..101c6d2 100644
--- i/plugin/grepper.vim
+++ w/plugin/grepper.vim
@@ -733,7 +733,9 @@ function! s:run(flags)
   if has('win32')
     let cmd = 'cmd.exe /c '. s:cmdline
   else
-    let cmd = ['sh', '-c', s:cmdline]
+    let cmd = py3eval(printf(
+          \ '__import__("shlex").split(%s)',
+          \ substitute(string(s:cmdline), "''", '\\''', 'g')))
   endif
 
   let options = {
```
(I know you probably do not like this, even when ported to VimL, but wanted to leave it here anyway)

**Comment by mhinz** [comment]
This is expected. The Grepper prompt should act exactly the same as the shell.

For `rg foo\ &bar` in the shell, you get the same issue. If trying to match the actual string `foo &bar`, you need to use `rg foo\ \&bar`, or `rg 'foo &bar'`, or `rg "foo \\&bar"`. Same for the prompt.

The `substitute()` you quoted above is not meant to put an `\` in front of the `&`. It's needed so that `&` doesn't get replaced by the matched pattern (`:h s/\&`):

```vim
:echo substitute('rg --foo --bar $* .', '\V$*', 'foo\ &bar', 'g')
:echo substitute('rg --foo --bar $* .', '\V$*', 'foo\ \&bar', 'g')
```

**Comment by blueyed** [comment]
Thanks for the info.

As mentioned before it is rather inconvenient to have it behave like a shell often.

FWIW, I am using the following currently:
```diff
diff --git i/plugin/grepper.vim w/plugin/grepper.vim
index b9b45dc..811d842 100644
--- i/plugin/grepper.vim
+++ w/plugin/grepper.vim
@@ -737,8 +737,24 @@ function! s:run(flags)
   if has('win32')
     let cmd = 'cmd.exe /c '. s:cmdline
   else
-    let cmd = ['sh', '-c', s:cmdline]
+    " NOTE: requires \b to be quoted ("\\bword\\b"), or escaped 4 times
+    " (\\\\bword\\\\b) (instead of 3).
+    try
+      let cmd = py3eval(printf(
+            \ '[__import__("os").path.expanduser(x) '
+            \ .'for x in __import__("shlex").split(%s)]',
+            \ substitute(string(s:cmdline), "''", '\\''', 'g')))
+      " echom printf('%s => %s', s:cmdline, cmd)
+      if cmd is 0
+        " https://github.com/neovim/neovim/issues/8785
+        let cmd = ['sh', '-c', s:cmdline]
+      endif
+    catch
+      echom 'vim-grepper error with shlex.split: '.v:exception.' ('.v:throwpoint.')'
+      let cmd = ['sh', '-c', s:cmdline]
+    endtry
   endif
+  " echom 'vim-grepper: cmd: '.string(cmd)
 
   let options = {
         \ 'cmd':       s:cmdline,
```

**Comment by blueyed** [comment]
Just for reference: the "prompt_quote" setting is very useful in this regard: https://github.com/mhinz/vim-grepper/blob/ebe6d1ffd1fb2faada867c56a55f44cbaa0248e3/doc/grepper.txt#L161-L178
