### ISSUE TITLE
Feature request: Mapping to cycle through directories

### ISSUE THREAD

**Issue by stellarhoof** [mhinz/vim-grepper#167]
Being able to switch tools on the fly with `<TAB>` is a lifesaver. It reduces the combinatorial explosion of possible mappings (assuming you don't like to type `Grepper ....`). I've found that in my workflow there are 3 options I change quite often:
1. Tool
2. Directory
3. Side option (`-side`)

But being a vimmer I use mappings for common use cases, so I've got 8 different mappings of grepper (4 directory options * 2 side options). However the mental load to be aware which mapping to use beforehand is too much imo. I'd rather type the command. It'd be really useful if I could cycle through `g:grepper.dir` in the prompt like I do with `g:grepper.tools`. I also think other people might benefit from this? Since changing directories to grep in is a common use case.

**Comment by mhinz** [comment]
Thanks for the suggestion. I'll see if there a viable ways to do that.

**Comment by mhinz** [comment]
In the prompt you can now toggle the -dir and -side flags via `<c-d>` and `<c-s>`.

You can change the default mappings with `:h g:grepper.prompt_mapping_dir` and `:h g:grepper.prompt_mapping_side`.

**Comment by stellarhoof** [comment]
Thank you so much! I like the default mappings. They are intuitive. `<c-s>` doesn't conflict with readline bindings and readline `<c-d>` can be safely be overriden here since it doesn't apply to the prompt.
