### ISSUE TITLE
Highlight search terms

### ISSUE THREAD

**Issue by rstacruz** [mhinz/vim-grepper#17]
Any chance we can get the search terms highlighted? I'd imagine it'd be something like:

```vim
let @/="foo"
```

**Comment by mhinz** [comment]
I thought about this, but I'm not sure it's gonna work out.

I'd have to emulate all the regexp engines that grep tools use and it would have to be configurable in case someone needs to add a new grep tool. Unless there's a better way, this would be extremely lot of work.

**Comment by mhinz** [comment]
Whenever you use the operator (motions/visual selections), you should get perfectly accurate highlighting.

When you enter the query yourself at the prompt, grepper assumes some things, so there might be some false positives in some cases. It does simple transformations like these:

```
\bfoo\b  ->  \<foo\>
*?  ->  \{-}
+?  ->  \{-1,}
```

And with this, I consider this feature implemented!
