### ISSUE TITLE
can't open neovim-qt on windows10

### ISSUE THREAD

**Issue by kdurant** [mhinz/vim-grepper#170]
vim-grepper settings like below
```vimL
let g:grepper.dir = 'repo,file'
let g:grepper.repo = ['.git', '.hg', '.svn']
```
neovim-qt  can't open

**Comment by mhinz** [comment]
I can only guess that you missed the `let g:grepper = {}` before these two lines.  It should throw an error like `E121: Undefined variable: g:grepper` in that case. But that shouldn't keep neovim-qt from starting.

neovim-qt surely keeps a log somewhere?

**Comment by mhinz** [comment]
Since there's nothing I can do without more information, I'm closing this. Please feel free to reopen if this is still an issue.
