### ISSUE TITLE
Using `--column` with git grep

### ISSUE THREAD

**Issue by lbonn** [mhinz/vim-grepper#178]
Since git 2.19, the grep subcommand can be used with `--column`.

It's not as useful as ag, since it only shows the column of the first match for each line instead of two matches for the same line with different columns (haven't found a magic option to override this behaviour).

Still, it's always nice to have.

Here is a vimrc snippet to use the feature with vim-grepper:

```vim
if executable('git')
  let s:git_version = matchstr(system('git --version'), "\\S\\+\\ze\n")
  let column_supported = s:git_version !~# '^0\|^1\|^2\.[0-9]\.\|^2\.1[0-8]\.'
  if column_supported
    call extend(g:grepper, {
          \ 'git': { 'grepprg': 'git grep -nI --column',
          \          'grepformat': '%f:%l:%c:%m' }
          \}, 'keep')
  endif
endif
```

Making the default config depend on some command output is a bit ugly, so here some the options:

- do it anyway for maximum feature support
- add a note in the doc so that users can customize their config
- wait for git 2.19 to be sufficiently old so that this can become the new default
- drop it and tell users to use something else if they want columns
- a combination of these

**Comment by mhinz** [comment]
Yeah, that's always a problem. :\

I learned that using `executable()` (for version checks) a lot on initialization annoys people. Nowadays I prefer the conservative way: Only use a new feature when it's supported by older versions. I usually check which versions are shipped by the current macOS (2.17) and Debian stable (2.11, roughly 2 years old).

I'd suggest that, for now, we only change the default grepformat for future compatability (or in case people already use `git config grep.column true`):

```diff
diff --git i/plugin/grepper.vim w/plugin/grepper.vim
index e41e3e2..28d39f2 100644
--- i/plugin/grepper.vim
+++ w/plugin/grepper.vim
@@ -37 +37 @@ let s:defaults = {
-      \                    'grepformat': '%f:%l:%m',
+      \                    'grepformat': '%f:%l:%c:%m,%f:%l:%m',
```
