### ISSUE TITLE
Prompt not cleared of quotes when changing directory

### ISSUE THREAD

**Issue by stellarhoof** [mhinz/vim-grepper#183]
The following happens with `prompt_quote=2` and using `<c-d>` to cycle through directories

<img width="424" alt="screen shot 2018-10-29 at 5 20 41 pm" src="https://user-images.githubusercontent.com/4336260/47681112-02ea6980-db9f-11e8-845b-68481ccb3451.png">

**Comment by mhinz** [comment]
Fixed! ✨
