### ISSUE TITLE
Unknown function: chanclose

### ISSUE THREAD

**Issue by niklaas** [mhinz/vim-grepper#186]
I recently updated the plugin on my machine. Since then I get the following error message when searching for a string:

```
Error detected while processing function <SNR>66_parse_flags[72]..<SNR>66_start[17]..<SNR>66_run:                                                       
line   47:                                                                                                                                              
E117: Unknown function: chanclose
```
Steps to reproduce:

1. `:Grepper -tool rg`
2. Type `help` and press `<CR>`

What happens:

1. The error message (see above) appears
2. After hitting `<CR>` again I see the results of the search

This is my configuration in `.vimrc`:

```
let g:grepper = {}
let g:grepper.tools = ['rg', 'grep', 'git']
let g:grepper_jump = 1
```

**Comment by mhinz** [comment]
Please upgrade the plugin again. I removed that line since it's not clear that it ever provided an advantage.

And upgrade your Nvim as well. `chanclose()` was introduced in v0.3.0 and there were 3 other releases since then. :)

**Comment by niklaas** [comment]
I'll do all of that! :-) Thanks for your feedback!
