### ISSUE TITLE
Quickfix <cr> breaks after a few uses

### ISSUE THREAD

**Issue by amadeus** [mhinz/vim-grepper#187]
For some reason - I am finding that the `<cr>` key seems to break (by break i mean pressing enter just moves the cursor to the next line, does not select and jump to the target location) in the quickfix buffer after performing a few different searches.

It's hard for me to reproduce reliably, although I do wonder if it could be an issue related to vim?

**Comment by mhinz** [comment]
When it happens again:

- What does `:map <cr>` output?
- Does it work again after `:unmap <cr>`?

**Comment by amadeus** [comment]
```
:map <cr>
No mapping found
```

And `unmap` seems to fail as a result of that.

**Comment by amadeus** [comment]
And it seems to say that both when `<cr>` seems broken, and when it works 😳

**Comment by amadeus** [comment]
I wonder if it's related to this change: https://github.com/vim/vim/pull/3902

**Comment by mhinz** [comment]
Yeah, I just wanted to make sure that no other plugin is doing anything weird.

No mapping is good. Then `<cr>` defaults to opening the file in the quickfix list (according to `:h quickfix`, `/<enter>`.

- When `<cr>` stops working.. do `:cnext`/`:cprev` still work?
- Does `:set ft?` report `qf`?
- Does `:set buftype?` report `quickfix`?

**Comment by amadeus** [comment]
You figured it out!

`:set buftype?` was returning empty, since `:cnext` and `:cprev` worked fine.

Manually calling `:set buftype=quickfix` fixed the problem.

**Comment by mhinz** [comment]
Then you need to figure out which code is doing that. It's certainly not this plugin. :-)

**Comment by amadeus** [comment]
Thanks for the help debugging! Much appreciated.

Does this look to you like something that could be related? Or do you think this is more in plugin land?

https://github.com/vim/vim/issues/516

**Comment by mhinz** [comment]
If it was a plugin, `:verbose set buftype?` would print the Vim script which set the option last.

**Comment by amadeus** [comment]
```
  buftype=
        Last set from ~/.vim/bundle/vim-grepper/plugin/grepper.vim line 884 
```

Yeah, looks like this must be a vim issue

**Comment by mhinz** [comment]
Huh, this is super weird. That line just does `:copen` which explicitly says to set buftype to `quickfix`.

The function executing that line runs on the exit handler, so it might be a race condition in Vim.

Would be interesting to know if you can reproduce that with Nvim.

**Comment by amadeus** [comment]
Looks like it was a Vim bug after all:

https://github.com/vim/vim/pull/4056

**Comment by mhinz** [comment]
Ah, good to know. Thanks for the link!
