### ISSUE TITLE
Slow plugin initialization

### ISSUE THREAD

**Issue by stellarhoof** [mhinz/vim-grepper#188]
Using https://github.com/tweekmonster/startuptime.vim I can more accurately diagnose which scripts are taking longer to load than others. As you can see from the attached screenshot grepper takes quite a bit more time than other scripts. What matters here is relative speed (since I've got a pretty fast SSD), not absolute speed. After some investigation, it turns out that https://github.com/mhinz/vim-grepper/blob/32c002c239d1838636bd3787012dc319dc4c96ee/plugin/grepper.vim#L13 is the culprit, since it makes a system call to the git binary. Is there any way of optimizing the git version detection? Perhaps caching the result or providing an option so the user can opt-in to column-precision jumps? (which is what git's `--column` option is for)

![image](https://user-images.githubusercontent.com/4336260/54005929-51011200-4129-11e9-85f4-f9bab0599d92.png)

**Comment by lbonn** [comment]
Interesting, we've already discussed skipping this version check here: https://github.com/mhinz/vim-grepper/issues/178 but we've still added it later in https://github.com/mhinz/vim-grepper/commit/41310e3c62d0eda9e69c91a762ecfd05813cc236.

I would argue that startup speed is quite important as it can quickly go out of control with when using a lot of plugins (which is now common).

**Comment by mhinz** [comment]
Well, the alternative is removing that code again and losing the feature, unless people set `g:grepper.git` theirselves, which they usually don't.

Debian stable (Stretch) still uses git 2.11 and git 2.19 is needed. Debian testing (Buster) has git 2.20 and enters Full Freeze in a few days which means that the next Debian release will be around June. _Then_ we can assume that everyone should have an mostly up-to-date git and remove that check at all.

**Comment by mhinz** [comment]
Okay, I added an optimisation for Git now: https://github.com/mhinz/vim-grepper/commit/62bd03f0b9dc6ab5217aa164753337893faac890

If git is used and `g:grepper.git.grepprg` is still the default, it now checks for the git version only once at the first invocation of `:Grepper` and not at source time.

Another user reported a substantial startup time reduction. Please test the latest version!

**Comment by stellarhoof** [comment]
Definitely much faster:

![image](https://user-images.githubusercontent.com/4336260/55180097-469dcb00-515f-11e9-80dc-518f41d08880.png)
