### ISSUE TITLE
the Grepper operator does not seem to skip use git grep while not in a git repo

### ISSUE THREAD

**Issue by arecarn** [mhinz/vim-grepper#189]
When using the grepper operator, while editing a buffer that is in a git repository, but the vim's pwd is not inside that git repository, Grepper trys to use git grep instead of skipping it an using the next tool in grepper.tools.

**Comment by mhinz** [comment]
Right, that's an issue even without using the operator. Looking into it.

**Comment by arecarn** [comment]
Thanks!

**Comment by mhinz** [comment]
Okay, so I just had to remind my self how this plugin is working. *\*cough\**

The code that switches to the next tool outside of a git repo is now run for the operator itself. But the actual working directory isn't changed by default.

See `:h g:grepper.dir`. You probably want `:Grepper -dir repo` or `:Grepper -dir file`. These can be hardcoded as `let g:grepper.dir = 'repo,file'`.

Now I'm pondering making that the default instead of `'cwd'`.

**Comment by arecarn** [comment]
Hmm, I think your changes is not quite right since I'm still seeing git grep getting called when my pwd is not in a git repo. 

Here's an explanation of my situation:
g:grepper.dir = 'cwd'
pwd = /home
open buffer  = /home/repo/file.txt
where /home/repo is a git repository

If you use grepper inside the open buffer it will try to use git grep, but fail since the pwd is where git grep is called from is not a git directory.

I think you may want to run the bellow check inside s:run() on your working directory found with s:compute_working_directory() instead of the files directory. Instead of the similar check you run at the beginning of s:start()
```
f !empty(g:grepper.tools) && a:flags.tools[0] == 'git'
        \ && empty(finddir('.git', work_dir.';'))
    call remove(a:flags.tools, 0)
  endif
```

**Comment by mhinz** [comment]
The patch above wasn't meant to solve your issue. It was a related issue, though. Previously the operator never used the code for skipping git and now it does (when using in the right directory or the `-dir` option given).

Your solution of using `s:work_dir` happens too late though:

1.  When using the prompt it shows git but eventually uses another tool (or fail if git was the only tool).
1. The query will be escaped as if it was git, but that might not work at all for the next grep tool. 

But the general approach is fine, we just need to run `s:compute_working_directory()` much earlier, probably before `s:prompt()` in `s:process_flags()`.

I fix that later today!

> Also, I'd vote for leaving the g:grepper.dir default to 'cwd' :)

I agree. :] The default should be the least surprising action.

**Comment by mhinz** [comment]
It should work as expected now.

**Comment by arecarn** [comment]
It's working for me. Thanks for the great plugin!

**Comment by mhinz** [comment]
👍 Thanks for taking the time to create issue reports!

**Comment by Konfekt** [comment]
Somehow the fix might have introduced a regression, as now it is impossible for me to open a second tab in a different git repository and vim-grepper inside it: the working directory always switches back to that of the first tab.

**Comment by mhinz** [comment]
@Konfekt Can you create an issue for it with steps to reproduce it?
