### ISSUE TITLE
Question: -dir does not work as expected?

### ISSUE THREAD

**Issue by zgpio** [mhinz/vim-grepper#190]
# Environment
* NVIM v0.4.0-420-g29d6993cc
* Linux
# Reproduce
min init.vim
```vim
set rtp+=~/vim-grepper/
```
1. nvim -u init.vim
1. :Grepper -dir /usr/local/share/nvim/
Grepper did not search for content in the -dir directory

**Comment by mhinz** [comment]
That's not how the `-dir` flag works.

It doesn't take a directory, but a value of either `cwd` (default), `file`, `filecwd`, `repo`, or a combination of those.

See `:h :Grepper-dir` which points to `:h g:grepper.dir` which explains the values.
