### ISSUE TITLE
E117: Unknown function: <SNR>142_wrap

### ISSUE THREAD

**Issue by flipjs** [mhinz/vim-grepper#191]
When grepper is invoked and try to run any command (for example :quit), I'm getting this error:

E117: Unknown function: <SNR>142_wrap
E:15 Invalid expression: <80><fd>R142_wrap("\^M")

In order for me to quit vim, I have to use command history (q:) and select ':q' from the list.

The only way for me to continue using vim-grepper is to git checkout be91bd0 . So any commit from a55a14b (Prompt: refactor mapping handling) up to the latest commit, it won't work for me.

Steps to reproduce:

1. :Grepper -tool rg
2. Type any command, for example :help or :quit

No custom configuration.

**Comment by mhinz** [comment]
This is not coming from this plugin. Search your plugins for `s:wrap(`.

**Comment by flipjs** [comment]
Will do. Thanks!

**Comment by mhinz** [comment]
Should be fixed now!
