### ISSUE TITLE
Add cword query to history

### ISSUE THREAD

**Issue by pylipp** [mhinz/vim-grepper#196]
Using the prompt with `:Grepper`, vim-grepper will use `<cword>` as query if the query is empty. However, the query is not added to the history. Is this by intention?

Rationale:
Sometimes I grep for the cword, and right afterwards want to modify the query for another grep. It'd be convenient to be able to open the prompt again, go to the previous query, edit it (e.g. `C-f`) and grep again.

**Comment by mhinz** [comment]
That was not intended, but it should be fixed now!
