### ISSUE TITLE
Operator pending mode support?

### ISSUE THREAD

**Issue by bruno-** [mhinz/vim-grepper#2]
Hi,
I so badly wanted a plugin like this for a long, long time. Thank you for working on it!

I'm curious, is there a way to get operator pending mode working? I skimmed the source, but couldn't find this.

Basically, with `gs` being the vim-grepper mapping, I want to use the plugin like this `gsiw` to grep for the "inner word". Another example often used in practice is `gsi"`.

Thanks

**Comment by mhinz** [comment]
I'm glad you like it!

I forgot to reference this issue in the commit, but the operator was implemented here: 250e4ff7190ebe6aeb0422f0845d73be86985d66

**Comment by bruno-** [comment]
I just tried it, works great - thanks!

Glad you like tmux plugins :)
