### ISSUE TITLE
Have git grep search the whole repository regardless of pwd

### ISSUE THREAD

**Issue by jmdaly** [mhinz/vim-grepper#20]
Hey, thanks for the great plugin! I'm finding it really useful. 

Up until now, I've been using :Ggrep from Tim Pope's vim-fugitive plugin when grepping through a git repo. With that plugin, regardless of the present working directory (provided that it's somewhere within the git repo), :Ggrep will search through the whole repo for the search term. vim-grepper seems to follow the default git grep behaviour of searching the current directly and below. 

Is there a way to modify the behaviour of git grep in vim-grepper to have it search the whole repository regardless of which directory in the repo we are currently in?

**Comment by mhinz** [comment]
Hmmmm. If you don't mind a longer prompt, you should be able to do this:

```vim
let g:grepper.git = { 'grepprg': 'git grep -nI $* -- `git rev-parse --show-toplevel`' }
```

**Comment by jmdaly** [comment]
Awesome, that's exactly what I was looking for! Thanks for your quick response. I went with the approach of adding the following to my vimrc:

```
let g:grepper = {}
let g:grepper.git = { 'grepprg': 'git grep -nI $* -- `git rev-parse --show-toplevel`' }
```
This is doing exactly what I was hoping. An FAQ in the docs would definitely be helpful :) Thanks again
