### ISSUE TITLE
Issues with git worktree

### ISSUE THREAD

**Issue by mantognini** [mhinz/vim-grepper#202]
First of all, thanks for this great plugin!

I've noticed that the git grepper is not available when using worktrees.

The following setup code can be used to showcase the issue:
```
$ git init /tmp/main
Initialized empty Git repository in /tmp/main/.git/
$ echo "FIXME" > /tmp/main/README
$ git -C /tmp/main add /tmp/main/README
$ git -C /tmp/main commit -m "Add Readme"
[master (root-commit) 6be3d8f] Add Readme
 1 file changed, 1 insertion(+)
 create mode 100644 README
$ git -C /tmp/main grep FIXME
README:FIXME
$ git -C /tmp/main worktree add /tmp/copy
Preparing worktree (new branch 'copy')
HEAD is now at 6be3d8f Add Readme
$ git -C /tmp/copy grep FIXME
README:FIXME
```

As shown above, `git grep` works in both worktrees. The following also works as expected:
```
cd /tmp/main
nvim +':GrepperGit FIXME'
```
My quickfix window shows that `git grep` was indeed used.

However, the same command does not work in `/tmp/copy`. Instead, another tool is used (`ag` in my case).

How would I go about debugging this? (I'm not familiar with vim script/plugin and all...)

**Comment by mantognini** [comment]
Let me know if you have pointers on how to debug this. ;)

**Comment by mhinz** [comment]
I'm currently quite busy, but I try to get down to this before weekend. :)

**Comment by mhinz** [comment]
Sorry that it took so long. 🙏

It was a really simple issue. In linked working trees, `.git` is not a directory but a file pointing to the main working tree. Grepper didn't expect that and thought it was outside a git repo.

Now, Grepper looks for either `.git` directory or a `.git` file.

**Comment by mantognini** [comment]
This is really appreciated, a big thanks for your work!
