### ISSUE TITLE
'Grepper -tool rg' with add current dir to search path

### ISSUE THREAD

**Issue by yehuohan** [mhinz/vim-grepper#205]
I use the command below (windows with vim or neovim):

```
Grepper -noprompt -tool rg -query TextToSearch C:\path\to\search
```
then search path will append the current work (.) :

```
C:\path\to\search .
``` 

I have to add the following script to my vimrc to avoid this problem:

```
    let g:grepper = {
        \ 'rg': {
            \ 'grepprg':    'rg -H --no-heading --vimgrep' . (has('win32') ? ' $*' : ''),
            \ 'grepformat': '%f:%l:%c:%m',
            \ 'escape':     '\^$.*+?()[]{}|'}
        \}
```

I just remove the '.' when it's in win32, which will change the s:defaults.rg.grepprg in line45.
Is it necessary to keep the '.'?

**Comment by mhinz** [comment]
If there's nothing behind `$*`, it can be left away. It's only needed if the query is not the last thing in the command-line. So just `'grepprg': 'rg -H --no-heading --vimgrep'` is the same as `grepprg': 'rg -H --no-heading --vimgrep $*`.

Your version works with Vim, but unfortunately not with Nvim. When you do `jobstart('rg foo')`, then rg will try to find `foo` in the empty stdin (or whatever it's called on Windows), but it won't implicitly add the `.` itself, to force the search on the local disk like it would do in an interactive terminal.

I try to think up a better solution, but I'm not sure if there is one.

**Comment by yehuohan** [comment]
Think your explanation. And I think the script added in my vimrc is enough for me at present.
