### ISSUE TITLE
Feature request: no-side flag

### ISSUE THREAD

**Issue by omrisarig13** [mhinz/vim-grepper#206]
Hey @mhinz,
First of all, thanks for this plugin, it looks great and it make grepping work better for me.

I would like an option to use a flag of noside, like the other no-flags in the plugin (for example, noopen). In my configuration, I would like to use the side option by default, but sometimes have some queries in which I wouldn't like to open the new window at the side. I didn't find a way to do it with the current flags available.

If you could guide me through adding this feature, I might be able to add it myself if you would like, but from first look at the code it seems quite complicated to me, since I am not very familiar with vimscript yet.

**Comment by mhinz** [comment]
Hi and thanks! :)

You'd just need to change [this line](https://github.com/mhinz/vim-grepper/blob/a73a9dc920bd0b3ba8b298c258bd4d4814d9a162/plugin/grepper.vim#L560) to look like [these lines](https://github.com/mhinz/vim-grepper/blob/a73a9dc920bd0b3ba8b298c258bd4d4814d9a162/plugin/grepper.vim#L550-L558) (and then also move it above the `-cword` check for cleaner grouping).

Then, for `:Grepper -nos<tab>` to work, add `-noside` [here as well](https://github.com/mhinz/vim-grepper/blob/a73a9dc920bd0b3ba8b298c258bd4d4814d9a162/plugin/grepper.vim#L215-L218) (alphabetically sorted with the `-no*` options at the end).

**Comment by mhinz** [comment]
Merged!
