### ISSUE TITLE
Feature: specify directory to grep in

### ISSUE THREAD

**Issue by SevereOverfl0w** [mhinz/vim-grepper#208]
2 of https://github.com/mhinz/vim-grepper/issues/108 is what I'm looking for.  Specifically, I want to have a single mapping for searching my wiki,~/.config/nvim and that requires specifying where to search.

changing directory and changing back seems hard based on fzf's code & comments: https://github.com/junegunn/fzf/commit/942ba749c7971076a650b899b4d44e0cced5f167

**Comment by mhinz** [comment]
Okay, I'll add `-cd` for more convenience.
