### ISSUE TITLE
Feature: Show CLI for -query flag by default

### ISSUE THREAD

**Issue by grwlf** [mhinz/vim-grepper#209]
Hi. I often find it useful to show CLI even when -query flag is specified. AFAIK, currently users can't get this behavior without patching the sources.

Please consider adding this feature. One could use my hack as a reference.

https://github.com/grwlf/vim-grepper/commit/231d06df26ff9d5df38d82e63630eb868cd10e64

**Comment by mhinz** [comment]
But the prompt (what you call CLI) should be shown by default with `:Grepper -query foo`.

And your patch actually makes the opposite of what you say, it _disables_ the prompt.

If I understand you right, you simply want `:Grepper -noprompt -query foo` instead.

**Comment by grwlf** [comment]
Indeed, looks like the current version of Grepper does exactly this without additional hacks. Originally I used v.1.4 which is far behind HEAD as I can see now. Its documentation says
```
-query <query>       ....
                     And since the query is specified on the
                     commandline already, the search prompt is skipped.
```

Looks like it is already fixed in master, thanks!
