### ISSUE TITLE
Change in behaviour with GrepperOperator

### ISSUE THREAD

**Issue by jmdaly** [mhinz/vim-grepper#21]
I've set up the following mappings, as suggested by the documentation:

```
nmap gs  <plug>(GrepperOperator)
xmap gs  <plug>(GrepperOperator)
```

Up to and including commit c244743 the behaviour when using those mappings is as outlined in the documentation. That is, the motion selection is used to populate the search prompt.

Beginning with commit 7640a44, the behaviour changes. The search query appears to be executed as soon as the mapping is used, bypassing the presentation of the search prompt to the user. This causes problems in my use case, where git grep is the default search tool. If I'm in a file that is not part of a git repo and I use those mappings, git grep is executed by default, and the search will always return zero results.

I'm running the latest nightly build of neovim, and haven't had the chance to see if the issue is present in vim as well.

Thanks for your help!

**Comment by mhinz** [comment]
Oops, I refactored the code a bit and used the wrong default value in this case.

Thanks for reporting!

**Comment by jmdaly** [comment]
You're welcome, thanks for resolving it so quickly!
