### ISSUE TITLE
E900 when more than 4999 matches in Neovim

### ISSUE THREAD

**Issue by gravndal** [mhinz/vim-grepper#212]
After https://github.com/neovim/neovim/commit/2d4a37ebab354afb94dfe600b302d8a2b1f2d889 I get the following error twice when there are 5000 or more matches:

```
Error detected while processing function <SNR>132_on_stdout_nvim:
line   26:
E900: Invalid channel id
```

Steps to reproduce:
1. `yes abcdefg | pv -Sl -s 5000 > something`
2. run nvim with nothing but the default runtime + vim-grepper
3. `:GrepperGrep abcd something` or `:GrepperRg abcd something`

**Comment by mhinz** [comment]
Yeah, Grepper defaults to 5000 matches by default. I think I see the problem.

**Comment by mhinz** [comment]
Should work now. Thanks! ✨
