### ISSUE TITLE
"grepformat" with -l: match filename-only

### ISSUE THREAD

**Issue by blueyed** [mhinz/vim-grepper#219]
When using `-l` to list only files (e.g. with ripgrep) it would be helpful if the `grepformat` (used for `errorformat`) would contain `%f` to handle the filename-only result.

I can imagine having `%f` just by default (appended) always might make sense, but could also be added/used only when `-l` is used.  There are other options though that change the output etc, so something more flexible might make sense.

I'm not sure about adding unnecessary complexity here - so this is meant as a start for discussion/ideas.

**Comment by mhinz** [comment]
Let's go the simple route unless there's a real problem (something that can't be solved by configuration alone), thus just appending `%f` to the defaults.

As the README states, I won't add any complex features anymore. Only the usual maintaining work like bug fixes and small enhancements.
