### ISSUE TITLE
Using multiple custom tools only works with the first one

### ISSUE THREAD

**Issue by saaguero** [mhinz/vim-grepper#22]
I'm using the following configuration in order to customize the tools available for grepping:

```vim
  let g:grepper = {
      \ 'tools':     ['ag', 'csearch'],
      \ 'dispatch':  1,
      \ 'open':      1,
      \ 'switch':    0,
      \ 'jump':      0,
      \ 'ag': {
      \   'grepprg': 'ag --nogroup --nocolor --column',
      \   'grepformat': '%f:%l:%c:%m',
      \ },
      \ 'csearch': {
      \   'grepprg': '~/gocode/bin/csearch -n',
      \   'grepformat': '%f:%l:%m',
      \ }}
```

Then, using the command `:Grepper` only shows `ag` and hitting `TAB` doesn't change to `csearch`.

Also, when running the command `:Grepper -tool csearch` fails with an error `No such tool: csearch`. With `:Grepper -tool ag` works fine.

Grepper version d66c5fb

**Comment by mhinz** [comment]
`~/gocode/bin` is probably not in `$PATH`. All non-executables from `g:grepper.tools` will be filtered out. That way it gets pruned of all the default tools that are not available on the system. (https://github.com/mhinz/vim-grepper/blob/master/autoload/grepper.vim#L49)

I suggest to either put a symlink to csearch into a path from `$PATH` (or just add `~/gocode/bin` to it) or use the full path in `tools`, e.g.:
```vim
let g:grepper = {
    \ 'tools': ['foo', '/home/user/gocode/bin/csearch'],
    \ '/home/user/gocode/bin/csearch': .....
```
I'll commit 2 patches:

1) document that the tools in `g:grepper.tools` have to be executable
2) `expand()` the tools in `g:grepper.tools`, so you can use `~/gocode/bin/csearch` instead of `/home/user/gocode/bin/csearch`

Does this sound good to you?

**Comment by saaguero** [comment]
Thanks for your response, you were totally right.

Exposing the corresponding binaries in $PATH did the trick.

Documentation will be really good to have.

Go ahead with the second point if you want, not mandatory, but I think might be an easy tweak to avoid having this "issue" again.

**Comment by mhinz** [comment]
I like the simple elegance of `call filter(s:options.tools, 'executable(v:val)')`, but I guess we could make it way more convenient for the user to use any arbitrary name in `g:grepper.tools` like this:
```vim
for tool in s:options.tools
  if has_key(s:options, tool)
        \ && has_key(s:options[tool], 'grepprg')
        \ && !executable(matchstr(s:options[tool].grepprg, '^[^ ]*'))
    call remove(s:options.tools, index(s:options.tools, tool))
  endif
endfor
```

As always in programming, it's a code size vs. user convienience tradeoff. I'll have to sleep a night over this.

**Comment by mhinz** [comment]
Okay, `g:grepper.tools` allows arbitrary names now. This should resolve the original issue.

**Comment by saaguero** [comment]
Thanks for your work.

It works but with the full path, ie: `/Users/santiago/gocode/bin/csearch`. With `~/gocode/bin/csearch` it doesn't work, but I don't know if we want to allow that.

---
About overwriting ag, it's because in Windows I'm still using an older version that doesn't support `--vimgrep` parameter.  I didn't find a new binary.

**Comment by mhinz** [comment]
Argh, I said it before but forgot to include it in the patch itself. I added the missing `expand()` now. :-)

**Comment by saaguero** [comment]
Excellent, it works!

**Comment by mhinz** [comment]
Great!

One last question: is the `--nocolor` really needed? I hacked up a special case for ag that uses `ag --column --nogroup --noheading` for versions < 0.25.

**Comment by saaguero** [comment]
Well, now that you mention, it seems that it isn't strictly necessary. However I can't try it in Windows right now.

I would say go with it since it won't do any harm.

**Comment by mhinz** [comment]
I skipped the `--nocolor` since none of the default `grepprg` values don't use those "disable color" options.

Thanks for all the feedback, very appreciated!

**Comment by saaguero** [comment]
Thanks to you for this additional change!
