### ISSUE TITLE
How to close the search result window?

### ISSUE THREAD

**Issue by Leviathan1995** [mhinz/vim-grepper#222]
I bind the `F10` to open `vim-grepper`， but how can I close the result window by a map command?

**Comment by Leviathan1995** [comment]
ping @mhinz

**Comment by lbonn** [comment]
The result window is just a regular quick list window, this question is out of scope for vim-grepper I would say.

Personally, I use https://github.com/romainl/vim-qf:

```
nmap <silent> <Leader>eq <Plug>(qf_qf_toggle)
```

**Comment by adam505hq** [comment]
@Leviathan1995 You can simply use `:cclose` or example below to Toggle Search.

```
function! ToggleSearch()
    if empty(filter(getwininfo(), 'v:val.quickfix'))
        :Grepper
    else
        cclose
    endif
endfunction

nnoremap <C-f> :call ToggleSearch()<cr>

**Comment by Leviathan1995** [comment]
@adam505hq  Thanks!
