### ISSUE TITLE
Exiting grepper command line with <escape> runs the search

### ISSUE THREAD

**Issue by saaguero** [mhinz/vim-grepper#23]
- Run Grepper
- Write something (or not) and press `<escape>` to cancel the search
- It will execute the search instead of quitting it the same way as `<ctrl-c>` does.

**Comment by mhinz** [comment]
Should work now!

Actually it was kind of a known "problem" and hence I explicitely stated as such in the help. I made it working using another magic string now, since there's no other possibility in VimL. It's quite a hack, but works.

**Comment by saaguero** [comment]
Awesome, works perfectly. Thanks for your quick response / implementation!

**Comment by mhinz** [comment]
Thank you for the valuable feedback. :)
