### ISSUE TITLE
E475: Invalid argument: cannot have both a list and a "what" argument

### ISSUE THREAD

**Issue by jinyeow** [mhinz/vim-grepper#231]
Windows 10
Using ripgrep.

&grepprg = 'rg --column --no-heading --smart-case --follow --vimgrep'

Have also tried with none of the above flags as well as just '--vimgrep' flag.

Anyone else seen this error? Or can someone advise what is a "what" argument?

**Comment by mvanderkamp** [comment]
Yup I'm getting that error as well. Started happening after I built a new version of vim. This appears to be coming from the use of the vim function setqflist, or possibly setloclist, likely both. I suspect the call signature changed, or perhaps the way this plugin was using those functions was unintended and vim is just more vocal about an error that was always there.

**Comment by rockneverdies55** [comment]
Having the same issue.
