### ISSUE TITLE
No jump when using GrepperOperator

### ISSUE THREAD

**Issue by zhangchiqing** [mhinz/vim-grepper#24]
When I do `gsw`, it jumps to the first match. Is it possible to stop the jump?

I tried :
```
nmap gs <plug>(GrepperOperator)!
```
It doesn't work

**Comment by mhinz** [comment]
You'll have to disable jumping like this:
```viml
let g:grepper = { 'jump': 0 }
```

**Comment by zhangchiqing** [comment]
Awesome :+1: It works! Thanks @mhinz

**Comment by mhinz** [comment]
You're welcome!
