### ISSUE TITLE
qf window height

### ISSUE THREAD

**Issue by Trid-collab** [mhinz/vim-grepper#246]
Is there any way to increase the default quick fix window height , presently it just fits the search results

Also how do I change the default buffer search to rg instead of ag - I am on neovim nightly and rg 13 the latest version

**Comment by lbonn** [comment]
vim-qf can set another default height: https://github.com/romainl/vim-qf/blob/master/doc/qf.txt#L336

For rg/as, just modify the tools list, rg as first element should do it. See https://github.com/mhinz/vim-grepper/wiki/Add-a-tool
