### ISSUE TITLE
Position the location of the quick fix window

### ISSUE THREAD

**Issue by nhooyr** [mhinz/vim-grepper#25]
It'd be nice to be able to position the quick fix window that opens up exactly how you want it. 

I tried creating a mapping to not open the quick fix window with the flag 'noopen' and then open it with how I want, say 'bot copen' but this doesn't work because vim-grepper calls 'cclose' if nopen is set which closes the quickfix window right after its open where I want it. 

Is there any way to get around this? For now I just changed the command that opens the quick fix window from 'copen' to 'bot copen'. copen

**Comment by mhinz** [comment]
It should have used `:botright` right from the beginning, so I changed it to use that.

For local matches windows (just below the window and using only the width of that window) the location list should be used in the first place.

Is this fine for you?

**Comment by nhooyr** [comment]
@mhinz it'd be nice if I could specify the position in a variable or something. or some option instead of it being hard coded.

**Comment by mhinz** [comment]
What do you mean when you say position?

The quickfix window will always be at the bottom of the screen. When using `:botright`, it will use the full width. Not using `:botright` actually leads to the weird behaviour: Assuming there are 2 windows side-by-side, and you open the quickfix window from the left window, it will still be opened below the right one.

**Comment by nhooyr** [comment]
@mhinz oh thats perfect sorry thanks. I thought botright would actually do what it meant. As in the farthest bottom of the right most window.

**Comment by mhinz** [comment]
I admit it's a bit misleading. :-) Thanks for reporting!
