### ISSUE TITLE
Cycling via next_tool does not preserve search term

### ISSUE THREAD

**Issue by elasticdog** [mhinz/vim-grepper#26]
If I'm on Grepper's commandline and type a search term, and then cycle to the next_tool it's populating the search with a previous term and not preserving my current search. Even if you don't type anything and have a blank commandline, cycling will populate the previous search term as well. Please let me know if that doesn't make sense or you need a demonstration.

These are my applicable Neovim settings, if they should matter in this case:

```
Plug 'mhinz/vim-grepper'
let g:grepper = {
	\ 'tools':     ['ag', 'git', 'grep'],
	\ 'open':      1,
	\ 'switch':    1,
	\ 'jump':      0,
	\ 'next_tool': '<C-G>',
	\ }
nnoremap <C-G> :Grepper -tool ag<CR>
nnoremap <Leader>* :Grepper -tool ag -cword!<CR>
nmap gG <plug>(GrepperOperator)
xmap gG <plug>(GrepperOperator)
command! -nargs=* -complete=file Ag Grepper -tool ag -query <args>
```

**Comment by elasticdog** [comment]
Note, that is only appears to be populating the previous term after a usage of `cword` or the operator.

**Comment by mhinz** [comment]
Thanks for reporting! It should be fixed now.

**Comment by elasticdog** [comment]
Thank you for the quick fix...works great!
