### ISSUE TITLE
Conversion from/to PCRE / Vim regular expressions

### ISSUE THREAD

**Issue by blueyed** [mhinz/vim-grepper#28]
https://github.com/ervandew/ag provides a neat feature, which converts simple regular expressions back and forth, e.g. `\<`/`\>` to `\b`.
This allows you to use e.g. the Vim flavour in the prompt, and it will be converted for the external program(s).

See https://github.com/ervandew/ag/blob/master/autoload/ag.vim#L195

**Comment by mhinz** [comment]
Hi, I'm not ignoring you, I just haven't found time to look into it yet. :-)

**Comment by mhinz** [comment]
I'll convert some regexp to Vim format for the highlighting feature: #17.
