### ISSUE TITLE
<tab> command mode mapping after using vim-grepper

### ISSUE THREAD

**Issue by bruno-** [mhinz/vim-grepper#3]
Hi,
I think I found a bug with `<tab>` mapping in cli mode. Here's how I can consistently reproduce it:

- `,g` to get into vim-grepper mode
- hit `tab` a couple times
- quit vim-grepper mode
- enter vim's regular cli mode (with `:`)
- hitting `tab` produces `E492: Not an editor command: $$$mAgIc###`

I use vanilla vim 7.4 patch 768.

Thanks

**Comment by mhinz** [comment]
Hi,

I actually knew this would happen. At the moment Vim knows no way to completely restore a mapping, but I'll push a little helper function that hopefully works for most cases.

(And in another upcoming commit, I'll make the "switch" key configurable.)

**Comment by bruno-** [comment]
Hey, I just pulled the latest version of this plugin and this issue is gone.
I also see you made the key customizable.

Anyway, I think this one is safe to close now.

**Comment by mhinz** [comment]
Okay, thanks for the feedback!
