### ISSUE TITLE
Pressing escape does not cancel search

### ISSUE THREAD

**Issue by atn34** [mhinz/vim-grepper#30]
When I press escape while typing a query, the query is run like I pressed enter instead of cancelled. I think it should be cancelled.

**Comment by mhinz** [comment]
I have to ask: are you using the latest version? This was fixed 5 weeks ago.

**Comment by atn34** [comment]
I've updated, and indeed it's fixed. Thanks!

**Comment by mhinz** [comment]
Phew. :-)
