### ISSUE TITLE
Create your own operators

### ISSUE THREAD

**Issue by rgrinberg** [mhinz/vim-grepper#32]
I know that greppers allows you to create custom commands as wrapper but it would be nice if you could create your own operators as well. For example, I'd like a custom operator that adds the literal `-Q` flag to a search.

**Comment by mhinz** [comment]
Hmm, the simplest solution would be adding another entry to `g:grepper`. E.g.

```vim
let g:grepper = {
  \ 'ag': {
  \    'grepprg': 'ag --vimgrep',
  \    'operator': 'ag --vimgrep -Q',
  \ }}
```

**Comment by mhinz** [comment]
@rgrinberg *ping*

**Comment by rgrinberg** [comment]
I gave your snippet a try but the little flaw with this is that I still have to press <cr> at the end to run the search. A bit annoying...

**Comment by mhinz** [comment]
Wait, the snippet above was a suggestion how to implement this, there's no `operator` key yet. :)

If you want the operator to search right way, use something like:

```vim
let g:grepper = { 'prompt': 0 }
nnoremap <leader>g :Grepper -prompt<cr>
```

**Comment by rgrinberg** [comment]
Thanks @mhinz that works like a charm. The only blemish with your solution is that it's not clear how to define an operator (should work visual mode too) that actually prompts!. But since it's not useful for me I will not heckle you further.
