### ISSUE TITLE
Ability to exclude directories from search.

### ISSUE THREAD

**Issue by MeanEYE** [mhinz/vim-grepper#33]
After reading the documentation I failed to find anything related to this feature I'd like to have. My apologies if I missed it and it is indeed documented.

So, I have fairly large project and your plugin is really useful when refactoring and quick searching for things am not sure of their location. However, I do have `libraries/` directory which is filled with some annoying stuff which always makes my quickfix window unreadable. It would be incredibly useful if we could globally specify ignore list for search, but also have an option to specify ignore before starting a search.

Thanks!

**Comment by mhinz** [comment]
Grepper merely provides the means for easy access to the tools. You decide how they're run. Excluding directories should be by the tools.

E.g. the following searches "foo" without taking "libraries/" into account:

```sh
$ git grep 'foo' -- * ':!libraries'
```

So you do the same at the prompt:

```vim
git grep -nI> 'foo' -- * ':!libraries'
```

**Comment by mhinz** [comment]
@MeanEYE *ping*

**Comment by MeanEYE** [comment]
Ah sorry didn't know you were expecting my response. You can close the
issue as your suggestion works.
