### ISSUE TITLE
Proper way of setting the search path for sift and Neovim

### ISSUE THREAD

**Issue by moon-musick** [mhinz/vim-grepper#34]
I use `sift` almost exclusively in CLI. It seems the default Grepper configuration for `sift` includes `.` as a search path indicator. For all I see this setting makes restricting the search operation to a subdirectory quite difficult. Due to that I made a simple setup with the dot removed (as it is not mandatory when running `sift` via command line):

```vim
let g:grepper = {
  \ 'next_tool': '<C-j>',
  \ 'tools': ['sift', 'siftp'],
  \ 'sift': {
  \   'grepprg':     'sift -n --binary-skip $*',
  \   'grepformat': '%f:%l:%m',
  \   'escape':     '\+*?^$%#()[]' }
  \ }

command! -nargs=* -complete=file Sift Grepper -tool sift -query <args>

nnoremap gs <Plug>(GrepperOperator)
xnoremap gs <Plug>(GrepperOperator)
```

It seems to work well enough with 'vanilla' Vim (7.4, patches 1-1529, pi-rho PPA @ Ubuntu 14.04).

The same config yields the `E40: can't open error file` error with Neovim (0.1.3-dev from 'official' PPA) if I provide only the search pattern and not the path:

```
Error detected while processing function <SNR>214_on_exit:
line    4:
E40: Can't open errorfile /tmp/user/1000/nvimknG5hR/2
No matches found.% 
```

If I provide the path (either a directory name or just the dot) it works fine.

The behaviour persists if I load `vim` and `nvim` with only my vim-plug settings (only `set nocompatible`, `filetype plugin indent on`, and standard vim-plug startup).

There's a Neovim error I should take care of first most likely (and I just started using it), but perhaps you have some idea what might cause such behaviour on Grepper's part?

Thank you in advance for any answer and also for all the work on your plugins :smile:

**Comment by mhinz** [comment]
Hmmm!

1. I fixed something related to that "can't open errorfile" message 4 days ago. Could you check if you use the latest version?

2. That Neovim issue.. it is weird. `:!sift -n foo .` works, `:!sift -n foo` yields no output at all. Same for `:echo system('sift -n foo')`. Under the hood Neovim switched to using [libuv](https://github.com/libuv/libuv) opposed to Vim's handrolled solution.

I look into it!

**Comment by moon-musick** [comment]
I am at 382e480, current HEAD.

It might be a `sift` issue in fact. I check the `!sift -n foo` invocation on a laptop where I had a much older `sift` version installed (0.3.2), and it seems to work just the same as with `.`. Current version (0.8.0) yields `1` exit code and no apparently no results. The same with `echo system('sift -n foo')`, if I pass the path to the older version binary, it works.

I will open an issue in the `sift` tracker, quite likely it has nothing to do with Grepper.

**Comment by moon-musick** [comment]
Apparently terminal detection in `sift` is to blame for this behaviour.

Sorry for bothering you and thank you for your help.

**Comment by mhinz** [comment]
Ah, confirmed.

By the way, regarding your config this would have been enough:

```vim
let g:grepper = {
  \ 'tools': ['sift'],
  \ 'sift': { 'grepprg': 'sift -n --binary-skip' }
  \ }
```

Actually I'm pretty sure I had a reason why I appended the `.` in the default, so I guess that's another thing that changed in recent versions. I'll adjust the default.

**Comment by moon-musick** [comment]
Ah, you're right, leftovers from test configuration. Thanks :smile:

**Comment by mhinz** [comment]
It should now work as expected!

**Comment by moon-musick** [comment]
It does indeed. Thank you very much!
