### ISSUE TITLE
Add option to disable quickfix mappings

### ISSUE THREAD

**Issue by atn34** [mhinz/vim-grepper#36]
Adding quickfix mappings without an option to disable them makes this plugin interact poorly with plugins like https://github.com/stefandtw/quickfix-reflector.vim.

**Comment by mhinz** [comment]
The mappings got removed in favour of dedicated plugins.

**Comment by daGrevis** [comment]
_Ohh, this broke my setup._

Here's how to restore it to something really similar:

1) Install https://github.com/romainl/vim-qf,
2) Enable mappings with `let g:qf_mapping_ack_style = 1`;
