### ISSUE TITLE
Directory completion in prompt

### ISSUE THREAD

**Issue by kminh** [mhinz/vim-grepper#38]
Hi Marco, thank you for such a useful plugin, it's definitely the best grep plugin out there.

Is it possible to add directory completion in prompt? We can use `<C-P>` or `<C-N>` to toggle tools and reserver `<TAB>` for completing directory, just like when using the `-query` flag?

**Comment by mhinz** [comment]
> thank you for such a useful plugin, it's definitely the best grep plugin out there.

Thanks!

> Is it possible to add directory completion in prompt?

There's support for file completion in the prompt, although it's not as nice as the one normal file completion in the commandline.

You could play around with `:h 'wildchar'`, but the easiest solution would be to change the key for changing tools (see `next_tool` in `:h grepper-options`). Afterwards you can use `<tab>` for file completion.

E.g.

```vim
let g:grepper = { 'next_tool': '<c-x>' }
```

(Keep in mind that `<c-n>`/`<c-p>` are used for the query history, so I would suggest not overmapping those.)
