### ISSUE TITLE
What is the proper way to escape query when feeding to -query flag?

### ISSUE THREAD

**Issue by kminh** [mhinz/vim-grepper#39]
Hello again,

I'm trying to building my own command around `:Grepper`, however I don't know how I should escape a query when feeding it to the `-query` flag. I have tried `shellescape` and `escape` but none worked. When I try to grep something using the built-in operator, it seems that the query is shellescaped.

Any insight is appreciated.

**Comment by blueyed** [comment]
The following works with a custom command for me:

     command! -nargs=+ Agopen Grepper -open -noprompt -tool ag -query <args>

I use it through this (Zsh) shell function:

    viag () {
	(( $# )) || {
		echo "Usage: $0 <arguments to :Ag in vi>"
		return 64
	}
	local -a vi_cmd
	vi_cmd=(Agopen ${(q-)@}) 
	nvim -c "${vi_cmd}"
    }

E.g.:

    viag -s "reloading Zsh"

**Comment by mhinz** [comment]
@kminh Does the above suggestion work for you?

**Comment by mhinz** [comment]
Please reopen this if you can't get it to work.
