### ISSUE TITLE
Handle error from tools

### ISSUE THREAD

**Issue by blueyed** [mhinz/vim-grepper#54]
In case the tool returns an error, vim-grepper should display it and not consider it to be matches.

When leaving out the "query" with "ag", you will get the following line in the quickfix list, and the message "Found 1 matches." is displayed:

> || ERR: What do you want to search for?

I think the quickfix/location list should not get filled at all, and vim-grepper should display the error using `echohl` / `echom`.  This might not be easy with the synchronous Vim method, but Neovim's `on_exit` gets the status / exit code of the tool.

**Comment by mhinz** [comment]
The problem here is that it's hard to distinguish between no found matches (which also returns 1) and actual errors like `git grep <foo`. The latter doesn't even use `stderr`, otherwise one could detect it with the async handlers at least (but not with Vim's old `system()`).

Is there another approach?

**Comment by blueyed** [comment]
The case without `stderr` is difficult, but in general I would consider it to be an error if
 - exit code is != 0
 - stdout is empty
 - stderr is not empty

The nothing-found case would be "exit code != 0" and "stdout" is empty.
Given that, I could imagine some tools exiting non-zero for errors, but then print the error to `stdout`.

**Comment by mhinz** [comment]
> Given that, I could imagine some tools exiting non-zero for errors, but then print the error to stdout.

| command | output | return value |
|-----------|--------|-------------|
| `git grep abcdef` | no output | 1 |
| `pt abcdef` | no output | 0 |
| `git grep 'foo\('` | error message from git on stderr | 1 |
| `git grep <foo` | error message from shell on stdout | 1 |

It's a pain.. :sob:

**Comment by blueyed** [comment]
The different behavior could be configured using a flag on the tool then, using some sane default.

After all it might be easy: if the return value is != 0 and there is some output (stderr or stdout), it's an error?!

**Comment by mhinz** [comment]
> After all it might be easy: if the return value is != 0 and there is some output (stderr or stdout), it's an error?!

Well, it's certainly not perfect, but I'd accept that as a solution that captures _most_ errors.

As you said, cases like `pt abcdef` _could_ be captured, if we added another member to the tool dict that lists the accepted return values, but currently I'd like to avoid that. I presume it's a rather uncommon case anyway.

---

(I hate it to add such special cases, why can't software just be reasonable? We certainly need an ISO standard for grep tools!)

**Comment by mhinz** [comment]
Hmm, this is currently blocked because the Neovim doesn't seem to provide the correct return value to the exit handler.. I'm looking into it.

**Comment by mhinz** [comment]
The hardest thing about this change is a multi-line `:echomsg`...

**Comment by mhinz** [comment]
https://gist.github.com/mhinz/1e332b4552130fdc5bf36234fe4da754 Hmm..

Any idea how to get a multi-line error message + getting it logged in the message history?

**Comment by blueyed** [comment]
You want to log the error from the tools output, right?
Why not use it as-is and let (Neo)Vim wrap it?
(Had to think about https://github.com/neomake/neomake/blob/2d8d0e80fb092b5aa3704b096c590dc8223dd57f/autoload/neomake/utils.vim#L60-L82, which I came across - but it's more about avoiding the enter prompt.)

**Comment by mhinz** [comment]
The 'press enter' prompt is fine with me for multiline errors, but my problem is that only `:echomsg` logs the messages, but doesn't interpret newline characters. So, `s:error()` loops over a list of lines, which actually works when used manually, but not when called from the exit handler (then only the last line is shown).

**Comment by mhinz** [comment]
Both, Vim and Neovim, suffer from the same bug and redraw too often when using callback handlers. That is, we can't use `:echo` or any related command.

Another alternative would be creating a scratch window with the exact size of the error output and highlight everything as `ErrorMsg`.

But is this really better than the current situation where the error message is simply thrown into the quickfix window? You get the error message and still see your exact line used in the statusline.

**Comment by mhinz** [comment]
FWIW, the Neovim issue is tracked here: https://github.com/neovim/neovim/issues/5067

**Comment by purpleP** [comment]
+1 for this issue.

**Comment by blueyed** [comment]
What about checking if there are (only?) invalid entries in the quickfix list, and then opening it always?

I am OK with having the error there, but I am not opening it by default (but use jumping).

**Comment by mhinz** [comment]
@blueyed ^

**Comment by mhinz** [comment]
@blueyed 

Can this be closed? I don't see that the bugs will be squashed in the near or mid future. I think the current way is really simple and good enough.

**Comment by blueyed** [comment]
Yes, thanks a lot!
