### ISSUE TITLE
search with spaces doesn't work in windows without quotes

### ISSUE THREAD

**Issue by prabirshrestha** [mhinz/vim-grepper#55]
```
:Grepper -tool git
should have
```

![image](https://cloud.githubusercontent.com/assets/287744/16849621/2c5eb75e-49b0-11e6-9888-db55303f66a0.png)

Adding quotes works.

```
:Grepper -tool git
"should have"
```

Should vim-grepper auto add quotes or is this expected behavior?

**Comment by mhinz** [comment]
This is expected behaviour.

As shown in the statusline, the input is really just thrown onto a shell and there `git grep -nI should have` simply doesn't work. It behaves like this, so you can simply insert queries like `foo *.c` or even `foo | head -n2`.
