### ISSUE TITLE
Add option to force synchronous search

### ISSUE THREAD

**Issue by sergei-dyshel** [mhinz/vim-grepper#57]
currently I'm using
```
let w:testing = 1
``` 
but it would be great to have a proper way to do that :stuck_out_tongue_winking_eye:

**Comment by mhinz** [comment]
D'oh. Someone looked into the code. ;-) May I ask what's wrong the async search?

**Comment by sergei-dyshel** [comment]
I have  `jump = 0` and and use a custom implementation of `:cc`. In the past a had problems  with the user auto-command you supply so I ended with smth like:
```vim
function MyGrep()
Grepper " ...
call MyCC()
```
Now the default async behavior breakes this. When I get to my workplace, I'll try autocommand again, may be it will work now :smile:

**Comment by mhinz** [comment]
Yea, I'd prefer fixing any issues over adding workarounds.

**Comment by sergei-dyshel** [comment]
Ok, here is minimal vimrc which reproduces the problem I've encountered:
```vim
set nocompatible

let dotvim = $HOME . '/temp/.vim'

execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs ' .
      \ 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim',
      \ dotvim)

execute "set rtp+=" . dotvim
call plug#begin(dotvim . '/plugged')

Plug 'mhinz/vim-grepper'
let g:grepper = {
    \ 'tools': ['ag', 'git'],
    \ 'open':  0,
    \ 'jump':  0,
    \ 'switch': 0,
    \ 'prompt': 1,
    \ }

autocmd User Grepper call MyCC()

call plug#end()

filetype plugin indent on
syntax on

PlugUpdate

function! MyCC()
  cc 1
endfunction
```
Just change `dotvim` to smth suitable for you and run it with `vim -u ...`. Then run `Grepper` and it should jump to the first error (I know this is the same as `jump = 1` but that's just an example).

But there is no syntax highlighting! That's the bug :smile:

**Comment by mhinz** [comment]
Autocmds don't nest. But `:cc` triggers a few, but not when called from a "norma" autocmd. This should work:

```vim
autocmd User Grepper call nested call MyCC()
```

-> https://github.com/mhinz/vim-galore#nested-autocmds :-)

**Comment by sergei-dyshel** [comment]
Works! Thanks! Closing

**Comment by sergei-dyshel** [comment]
I should take another look at Galore :smile:
