### ISSUE TITLE
Quitting command window should cancel search

### ISSUE THREAD

**Issue by atn34** [mhinz/vim-grepper#58]
To be consistent with other command windows like `q:`, vim-grepper should only execute the search if the user hits enter. If the users quits the window with :q, the search should be cancelled.

Step to repro:

:Grepper
<c-f>
:q

(I'm using version b8f52fc)

**Comment by mhinz** [comment]
Command window? Do you mean at the prompt?

**Comment by atn34** [comment]
Ahh sorry, my repro steps markdown formatting must have been bad.

Steps to repro:

```
:Grepper
<C-f>
:q
```

**Comment by mhinz** [comment]
Oh. Yea, I should have believed you when you said "command(-line) window", but honestly, I never use `<c-f>` myself, only `<c-n>`/`<c-p`, so it didn't came to mind.

You can leave the cmdwin with the current line with `<c-c>`. So, hitting `<c-c>` twice hopefully works for you.

I can't come up with a better idea anyway. It would probably involve hooking into `CmdwinEnter` and setting/unsetting global variables to detect if the cmdwin was opened from a Grepper prompt.. pretty messy.

**Comment by mhinz** [comment]
By the way, in case it isn't clear: When you use `:q` in the cmdwin, you discard the cmdwin _and_ the prompt, which leads to an empty query which means using the word under the cursor as query.

**Comment by mhinz** [comment]
Okay, I thought about this for a while and every other solution, than simply using what Vim already provides, would involve wild hacks that probably break in some cases.

So, please use `<c-c><c-c>` in your case!

**Comment by atn34** [comment]
Gotcha. Thanks!
