### ISSUE TITLE
search results for current word in current file only

### ISSUE THREAD

**Issue by mellery451** [mhinz/vim-grepper#62]
I would like just the simple mapping to search for the current word in the current buffer - I've tried:

`nnoremap <leader>sf  :Grepper -tool ag -cword -noprompt $* %<cr>
`

...which doesn't produce errors when invoked, but tells me "no matches" which of course is nonsense because the current word is by definition in the current file (the buffer is saved). How can I debug what's going wrong here?

**Comment by lbonn** [comment]
You can use the `$.` placeholder to designate the current buffer (see #27) and define a new tool.

For example (taken from my config):

```
let g:grepper = {
    \ 'tools': ['git', 'ag', 'grep', 'localgrep'],
    \ 'localgrep': { 'grepprg':    'grep -RHn $* $.',
    \                'grepformat': '%f:%l:%m',
    \                'escape':     '\$.*[]%#' },
    \}
nnoremap <Leader>gl :Grepper -tool localgrep -cword -noprompt<CR>
```

**Comment by mellery451** [comment]
@lbonn - that works perfectly - thanks!
