### ISSUE TITLE
File autocomplete in prompt mode

### ISSUE THREAD

**Issue by m1foley** [mhinz/vim-grepper#68]
It would be nice if prompt mode had the equivalent of `-complete=file`. Since it currently doesn't, I'm searching in command mode instead:

```vim
  " :Rg or double-backslash for Grepper command
  command! -nargs=+ -bang -complete=file Rg GrepperRg <args>
  nmap \\ :Rg<Space>
```

**Comment by mhinz** [comment]
Oh, it has a custom file completion (which unfortunately can't be as smooth as the built-in `-complete=file` equivalent), try `<c-d>`.

Alternatives:

*1)* Change Vim's key trigger key: `:h 'wildchar'`

*2)* See `next_tool` in `:h grepper-options-tools`. Afterwards you can use <kbd>Tab</kbd> (which is the Vim default) for tab completion.

**Comment by m1foley** [comment]
Thanks for being so responsive, and for maintaining this plugin!

**Comment by mhinz** [comment]
I'm glad if others deem it useful. :-)
