### ISSUE TITLE
git grep fails when search text contains "("

### ISSUE THREAD

**Issue by pabloxxl** [mhinz/vim-grepper#7]
While I am searching text containing "(" (like function name), I get following error.

git grep -n> do(/bin/bash: -c: line 0: syntax error near unexpected token `('
/bin/bash: -c: line 0: `git grep -n do( 2>&1| tee /tmp/vwNfw38/2'

I think "(" should be escaped somehow, or entire text should be covered by quotation marks.

**Comment by mhinz** [comment]
I'll look into it after merging #6 later today.

**Comment by mhinz** [comment]
This should work now.

Just remember to use quotes as shown in the demo gif and also remember that `git grep` tries to interpret regular expressions by default. Use `git grep -F 'func(foo)'` for searching for fixed strings.
