### ISSUE TITLE
Neovim: lines/results are not joined properly

### ISSUE THREAD

**Issue by blueyed** [mhinz/vim-grepper#71]
I am often seeing that results are split like the following (searching for `approx` in pytest master):

```
51 testing/python/approx.py|235 col 26| assert [1,                                           
52 ||  2] != approx([1])                                                           
53 testing/python/approx.py|236 col 26| assert [1, 2] != approx([1,2,3])
```

This might be related to how data gets to the stdout handler, see https://github.com/neovim/neovim/issues/3555.
In Neomake we're using this: https://github.com/neomake/neomake/blob/39597271007e6b16e95f9e6d1c30cecc274e0eb9/autoload/neomake.vim#L712-L717

**Comment by mhinz** [comment]
Thanks for the reminder! (I remember you telling me about this before on Gitter..)

**Comment by blueyed** [comment]
Thank you!

**Comment by mhinz** [comment]
BTW, do you happen to know if there are similar problems with Vim?

**Comment by blueyed** [comment]
I think in raw mode it behaves like Neovim, but otherwise it's line-based.
