### ISSUE TITLE
Open quickfix items similar to ag

### ISSUE THREAD

**Issue by nguyenj** [mhinz/vim-grepper#72]
Is it possible to open quickfix items similar to Ag?

This is my current workaround:

```
autocmd BufReadPost quickfix nnoremap <buffer> q :q <CR>
autocmd BufReadPost quickfix nnoremap <silent> <buffer> h  <C-W><CR><C-w>K
autocmd BufReadPost quickfix noremap <silent> <buffer> H  <C-W><CR><C-w>K<C-w>b
autocmd BufReadPost quickfix noremap <silent> <buffer> o  <CR>
autocmd BufReadPost quickfix noremap <silent> <buffer> t  <C-w><CR><C-w>T
autocmd BufReadPost quickfix noremap <silent> <buffer> T  <C-w><CR><C-w>TgT<C-W><C-W>
autocmd BufReadPost quickfix noremap <silent> <buffer> v  <C-w><CR><C-w>H<C-W>b<C-W>J<C-W>t
```

This is what Ag does, https://github.com/rking/ag.vim/blob/master/autoload/ag.vim#L162-L167.

**Comment by mhinz** [comment]
Please see `:h grepper-mappings`.

[We once had such mappings](https://github.com/mhinz/vim-grepper/commit/fadf0a3b0f1ef501db9f6935b50a184fe83cd00b), but obviously everyone wants something else, so we removed them in favour of dedicated plugins like [vim-qf](https://github.com/romainl/vim-qf) or [QFEnter](https://github.com/yssl/QFEnter).

**Comment by Leandros** [comment]
How do I use QFEnter with vim-grepper, though? It seems like vim-grepper is overriding the QFEnter bindings:
<img width="484" alt="screen shot 2017-02-15 at 15 09 38" src="https://cloud.githubusercontent.com/assets/396475/22977899/cf4eb254-f390-11e6-91b5-ace0805af3fa.png">
