### ISSUE TITLE
tabe on result

### ISSUE THREAD

**Issue by voxsim** [mhinz/vim-grepper#74]
Is it possible to open a row in a new tab? Like doing tabe <your file>?

I read the documentation and i did't understand if it is possible..

thanks,
Simon

**Comment by mhinz** [comment]
You mean from the quickfix window? Then no, Vim doesn't define any mappings for it (only `<cr>` and `<c-w><cr>`) and the plugin doesn't do so on purpose.

As noted in `:h grepper-mappings`, you could use [vim-qf](https://github.com/romainl/vim-qf) instead. If you use that plugin and set this in your vimrc:

```vim
let g:qf_mapping_ack_style = 1
```

Then you can simply use `t` on any quickfix entry ("row") to open it in a new tab.

--

Or you [do what the plugin does](https://github.com/romainl/vim-qf/blob/master/after/ftplugin/qf.vim#L44) and define the mapping yourself:

```vim
autocmd FileType qf nnoremap <buffer> t <c-w><cr><c-w>T
```
