### ISSUE TITLE
searching into current buffer (again)

### ISSUE THREAD

**Issue by teto** [mhinz/vim-grepper#75]
I read:
https://github.com/mhinz/vim-grepper/issues/27
https://github.com/mhinz/vim-grepper/issues/62

but still have some questions:
- is it necessary to define a grepprg to look into the current buffer ? can't I use an existing grepper "tool" such as ag and dynamically tell it to look into current buffer ?
For instance, I have `nnoremap <leader>ag  :Grepper -tool ag  -open -switch` so I would like to type <leader>ag and then manually write sthg to make a search in the current buffer, is that possible.
I suppose the "$*" placeholder is only replaced if in grepprg ?
- Incenditally, I wanted to check the g:grepper default config and did :echo g:grepper but it is not defined by default (I found the defaults in s:options in autoload/grepper.vim) but wouldn't it be better to define g:grepper globally ? so that the user can see the default config ?

**Comment by mhinz** [comment]
**1)**

Working at it. ;]

It will add a new key "grepprgbuf" for the tools, e.g. grep will look like this by default:

```vim
      \ 'grep':          { 'grepprg':    'grep -Rn $* .',
      \                    'grepprgbuf': 'grep -Hn $* $.',
      \                    'grepformat': '%f:%l:%m',
      \                    'escape':     '\^$.*[]' },
```

Then, `grepprgbuf` will be used on `:Grepper -buffer`.  On `:Grepper -buffers`, `grepprgbuf` will be used as well, but the `$.` will simply be replaced by `$+`.

**2)**

Should be doable!

**Comment by mhinz** [comment]
@teto I added `-buffer` and `-buffers`. Does it work as expected for you?

**Comment by teto** [comment]
It does. Now grepper is perfect.

**Comment by mellery451** [comment]
love this new feature - small bug report: If any of the buffers have a space in the name, it seems to parse that as two or more args...

**Comment by mhinz** [comment]
@mellery451 Oops. Thanks for pointing that out. Should work now!

**Comment by mellery451** [comment]
👍  confirmed - works great now

**Comment by geneotech** [comment]
Much thanks! This feature has also made me win at grep.
