### ISSUE TITLE
Cannot use navigation keys (arrows, home, end) in search prompt on Windows

### ISSUE THREAD

**Issue by austincrft** [mhinz/vim-grepper#78]
## Technical Info

| Spec        | Description                                             |
| ------------| ------------------------------------------------------- |
| OS          | Windows 8.1                                             |
| Terminal    | ConEmu                                                  |
| Vim Version | VIM - Vi IMproved 8.0 MS-Windows 64-bit console version |

## Issue

Cannot use navigation keys (arrows, home, end) in search prompt

## Steps to Recreate

1. Run `:Grepper` command (defaults will do)
2. In search prompt press a navigation key (arrows, home, or end)

Expected Output: Performs navigation motion
Actual Output: Closes search prompt

## Notes

I can use the navigation keys while running commands in Vim. This works fine in Windows GVim and on my Arch machine.

## Current Vimrc
http://pastebin.com/jHsXSdt9

**Comment by mhinz** [comment]
I assume the same happens in the normal command-line, eh?

**Comment by austincrft** [comment]
Hm, it does work with cmd, actually. It does seem to be an environment issue.

I'll comment back here if I happen upon a solution. Maybe it'll help someone in the future.
