### ISSUE TITLE
b:grepper = buffer-local g:grepper

### ISSUE THREAD

**Issue by Konfekt** [mhinz/vim-grepper#80]
In a git repo, prefer`git` as grep tool, otherwise fall back to `grep` say. At the moment, the auto command
```vim
autocmd BufWinEnter * let g:grepper.tools = (exists(':Git') ? ['git', 'grep'] : ['grep', 'git'])
```
(provided that vim-fugitive is installed) achieves this. But cleaner seems 
```vim
autocmd BufWinEnter * if exists(':Git') | let b:grepper.tools =  ['git', 'grep'] | endif
```
and `Grepper` falling back to `let g:grepper.tools = ['grep', 'git']` otherwise.

**Comment by mhinz** [comment]
Can you think up any use case where exposing the other keys of `g:grepper` makes sense as well or should we just go for `b:grepper_tools`?

**Comment by mhinz** [comment]
I think we should go the whole way, but since VimL doesn't support [autovivification](https://en.wikipedia.org/wiki/Autovivification), the autocmd would look like this:

```vim
autocmd BufWinEnter * if exists(':Git') == 2 | let b:grepper = { 'tools': ['git', 'grep'] } | endif
```

**Comment by Konfekt** [comment]
Thanks! Fantastic. Works flawlessly.

**Comment by Konfekt** [comment]
> Can you think up any use case where exposing the other keys of g:grepper makes sense as well or should we just go for b:grepper_tools?

Yes, for example in some repos you might want
```
 'git':           { 'grepprg':    'git grep -nI',
```
and in others also search in the untracked files, 
```
 'git':           { 'grepprg':    'git grep -nI --untracked',
```
Or in some dir's also search through all ignored files by `ag`,
```
'ag':            { 'grepprg':    'ag --vimgrep -U',
```

**Comment by mhinz** [comment]
Right, thanks for the feedback!
