### ISSUE TITLE
git grep and absolute file paths

### ISSUE THREAD

**Issue by phcerdan** [mhinz/vim-grepper#82]
git grep does not show absolute file paths. The closer option I've found is `--full-name` which shows paths relative to the project root.
I cannot open up the quicklist results generated from :GrepperGit, because I end in a new buffer because the incorrect path.

How do you workaround this? Am I missing a git grep option to show a full path?

**Comment by mhinz** [comment]
How do open the quickfix entries?

By default, `<cr>` should work as expected, even when the current working directory was changed. Try: `:GrepperGit ... | ls!`. You will see all files that had matches got added to the buffer list as unlisted buffers. Then change the working directory and compare the filenames afterwards with `:cd /tmp | ls!`, they should have changed to absolute ones.

I can only guess that you're using a plugin or custom mappings that works on the actual filename displayed in the quickfix window. That approach will break in many cases, I guess.

**Comment by phcerdan** [comment]
Thanks @mhinz. This is my little hack for searching in git repositories completely independent of current working directory using `git grep`. I usually use it to search in the source code of a external library.

`git grep` only shows relative paths from the git project (even with the option `--full-path`). So we use `sed` to generate the absolute path: 
```vim
let g:grepper.gitSF =
   \ { 'grepprg': 'git -C ' . g:sourceFolder . ' grep -nI $* | sed s:^:' . g:sourceFolder .'/: --' }
```
then, the quickfix window will display them relative to the vim cwd, as @mhinz pointed out, but we will be able to open them. Without the `sed` part, the quickfix window displays the relative paths shown by `git grep`, but they do not correspond to the right file.

This is configuration for this, just in case.
```vim
function! SetSourceFolder(path)
    let g:sourceFolder=a:path
    " Set vim-grepper {{{
    if !has_key(g:grepper, 'tools')
      let g:grepper.tools = []
    endif
    " git
    if !v:shell_error
      if index(g:grepper.tools,'gitSF') == -1
        let g:grepper.tools = g:grepper.tools + ['gitSF']
      endif
      let g:grepper.gitSF = g:grepper.git
      let g:grepper.gitSF =
            \ { 'grepprg': 'git -C ' . g:sourceFolder . ' grep -nI $* | sed s:^:' . g:sourceFolder .'/: --' }
    endif
    execute 'command! -nargs=+ -complete=file GrepperGitSF'
          \ 'Grepper -noprompt -tool gitSF -query <args>'
    " }}}
endfunction
com! -nargs=1 -complete=file SourceFolder call SetSourceFolder(<q-args>)

```
