### ISSUE TITLE
Project root finder

### ISSUE THREAD

**Issue by lbonn** [mhinz/vim-grepper#83]
vim-grepper is difficult to use with multiple projects (eg: git repos) at once because it searches from the vim current directory.

This is partially solved by the faq entry about git grep: https://github.com/mhinz/vim-grepper/blob/3a0157f07090136caaa257c715a1e57b8e4f8ca2/doc/grepper.txt#L358

However, it does not solve all of the use cases:

If we have a directory with two git repos: `d/a` and `d/b`, `git grep` won't work if we open a file of `a` from vim in `d` (ag or a friend can help us here but it will search both repos). If we start from `a` and open a file in `b`, we won't be able to search the `b` repo from here in any case without changing  the vim's current dir.

This is probably a bit controversial because it would probably add some complexity to vim-grepper but it would be nice to have a toggleable heuristic to detect the wanted directory from the current buffer.

This is what ctrlp does:
https://github.com/ctrlpvim/ctrlp.vim/blob/a99119abbbae346029ae3befc1bbf7b707098cf3/doc/ctrlp.txt#L187

`:Ggrep` from fugitive works similarly and find the git repo in which the current buffer lies.

If it's not in the project's scope, it could also be a subject for the FAQ or the wiki but I suspect it would not be easy to add this in a vimrc.

**Comment by mhinz** [comment]
Sure, no problem. :)

```
:Grepper -dir <value>
```

Whereas _value_ would be one of these: `root` (**r**), `cwd` (**0**), `file` (**a**) or combinations thereof, e.g. `:Grepper -dir root,file`, which should be the default (like in ctrlp).

**c** and **w** don't look too useful to me.

What do you think?

**Comment by lbonn** [comment]
Cool, this looks pretty good.

**Comment by mhinz** [comment]
Please pull the latest changes.

By default, it will still use the current working directory, but you can use this already:

```
:Grepper -dir repo
:Grepper -dir file
:Grepper -dir repo,file
```

**Comment by mhinz** [comment]
Added the documentation: `:h g:grepper.dir` and `:h :Grepper-dir`.

All I could think of is implemented, so I'm closing this now.

But please report back if it works as you expected it to work. (It does for me. ;-))

**Comment by lbonn** [comment]
So far, everything works fine for me.

Maybe the FAQ entry about the git root could point to this option instead of suggesting to change `grepprg`.

Thanks for this awesome plugin :)

**Comment by mhinz** [comment]
Ah, good catch! I'll reword that FAQ.

Thanks for bringing this up.

**Comment by lbonn** [comment]
Follow-up on the discussion about the `-dir` switch:

I found that the equivalent of the `c` value in ctrlp can indeed be useful and added it to my fork: https://github.com/lbonn/vim-grepper/commit/aa28dbc4d606570d44f31b9ffbe80b73380bc3c1. The current `file` flag had to be renamed to `filecwd` but I don't know if it's such a good name.

Use case: starting a search from a directory (netrw buffer, or dirvish in my case) limited to the currently displayed directory instead of the whole project.

**Comment by mhinz** [comment]
Ah, I see. I like that commit. Do you care to create a PR for it?

**Comment by mhinz** [comment]
Another thing that I just noticed: https://github.com/mhinz/vim-grepper/blob/01fdce1c02f31bdffdc89ce6978fccbf776f4a17/autoload/grepper.vim#L330-L338

So, we try finding the repo root beginning from the _current directory_. It would probably make more sense beginning from the _directory of the current file_, right?

**Comment by lbonn** [comment]
You're talking about the `finddir`? It looks like it works correctly.

By reading `:help file-searching`, it would seem that the `path` argument should be `./;` but actually `.;` works the same way and starts from the current file path (at least it did when I tried).

However, when I looked about your remark, I noticed that the local cwd is not restored to the previous value after a search in non-cwd dir mode. This might be tricky to get right though... Even more as the plugin is asynchronous?

The grep command of fugitive does a little dance like this: save current dir, change to repo's and switch back in a `finally` block.

**Comment by mhinz** [comment]
Actually, it's not tricky at all. The same method using `finally` can be used by simply wrapping `job_start()` (you don't have to wait until the job finished before switching back).

Neovim's `jobstart()` makes it even easier by taking a `cwd` option.

I do that in Sy already: https://github.com/mhinz/vim-signify/blob/master/autoload/sy/repo.vim#L84-L113

Someone just has to take the time to do it.. *hint hint*

**Comment by lbonn** [comment]
I tried a simple wrap in `s:start()`.

Here is the tricky bit: the paths in the quickfixt are still relative to where the search was launched and don't work when returning to the original working directory.

Maybe the path needs to be translated or maybe it's enough to do another temporary chdir during the `addexpr` calls (I'm not entirely clear on how vim handles paths in the quickfix list).

I'll take another look and keep you posted.
