### ISSUE TITLE
Only match whole words with -cword?

### ISSUE THREAD

**Issue by lbonn** [mhinz/vim-grepper#87]
It would behave like `*` which is handy when searching for small words.

I made a small prototype here (based on my pull request #86):

https://github.com/lbonn/vim-grepper/commit/e9f4b945a95f84bf26bcfb94f61abdbea8b5057c

It's not tool-agnostic which, I think, is unavoidable. I don't use Windows but I suppose it won't work with `-tool findstr`.

For these reasons, it should probably be made optional.

Remaining issues:

- breaks highlighting, I don't really know how to fix this
- should only be available with supported tools

**Comment by mhinz** [comment]
Hmm, can you give an example problem?

**Comment by mhinz** [comment]
I'm closing this since I'm going into maintenance mode for this plugin. I'll still fix bugs but I won't add new features on my own. PRs, given they're small enough and I don't need much time to review them, are welcome.

Hint: The best solution for this issue would be to add _yet another_ key for each [tool](https://github.com/mhinz/vim-grepper/blob/master/autoload/grepper.vim#L24-L26). E.g. `cword`.

**Comment by toiffel** [comment]
Hello @mhinz, I would also be interested to have this in vim-grepper. Could you please suggest, what should this new `cword` key contain?

Most tools have a dedicated command-line option for whole words matching like `-w, --word-regexp` but unfortunately findstr doesn't have it. So we can't specify command-line options in `cword` key.

Alternatively, we could use some substitution patterns in `cword` key, e.g. `\b$*\b` or findstr-specific `\<$*\>`, where `$*` is replaced with the current word under the cursor. This is also similar to how `grepprg` key works. What do you think? Thanks!

**Comment by mhinz** [comment]
From these two solutions I'd probably go with the latter.

We would have to introduce a new key `wordanchors` (seems to be more fitting than `cword`) that takes a 2-element list like `['\<', '\>']` or `['\b', '\b']` etc.

.oO(This is all easy to do, but I recall there were some issues with escaping..)

**Comment by toiffel** [comment]
Thank you for your suggestion!

Yeah, the trick is that the word under cursor should be escaped but `wordanchors` characters should not. I'll try to figure out how to implement this correctly and come back later.
