### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by GianniGi** [mhinz/vim-grepper#88]
OS: windows 8.1
grep: cygwin

when I use grepper, I obtain this error:

FINDSTR: Out of memory
[Quickfix List] findstr -rspnc:"keysearched" *

**Comment by mhinz** [comment]
Doesn't look like a problem with the plugin. Maybe `findstr` returned that because you started the search in a huge directory?

**Comment by mhinz** [comment]
As I said above, there's nothing I can do about that from the plugin. It's just that it tried searching all directories below the current one and that made the program run out of memory.

If you're using Windows, I strongly suggest setting up a Unix-like environment (Git bash, sysgit2, cygwin, etc.) and use one of the other tools instead. I added `findstr` so Win users have at least one supported tool by default, but I wouldn't really recommend it. It's certainly the worst one compared to all the other supported default tools. :)
