### ISSUE TITLE
Opening files from quickfix list

### ISSUE THREAD

**Issue by daGrevis** [mhinz/vim-grepper#9]
It would be nice to have an option to open files from quickfix list. I'd like to open file in current buffer or in a new tab.

**Comment by mhinz** [comment]
I'll look into it.

**Comment by daGrevis** [comment]
Thanks! :+1:

**Comment by mhinz** [comment]
You're welcome!

**Comment by kariya2** [comment]
Is there any way to open files in a new split?

**Comment by daGrevis** [comment]
@kariya2 Try [`vim-qf`](https://github.com/romainl/vim-qf). It allows to open split with `v` or `s`.
