### ISSUE TITLE
ERR on certain queries

### ISSUE THREAD

**Issue by amadeus** [mhinz/vim-grepper#91]
In a particular project I work in, when I perform an ag query from the root directory (it's a rather large project)I will sometimes get this error:

![example](https://dl.dropboxusercontent.com/s/x7rxfh2m2m6xnou/Developmentdiscord_2017-01-21_11-06-23.png?dl=0)

**Comment by mhinz** [comment]
Hmm, when it's prefixed with `ERR`, the error is coming from ag itself. Can you reproduce it when you manually run `ag --vimgrep web_canary` from the directory `:pwd`?

The only other thing I noticed is that the message says that it read (4gb - 1b) bytes for whatever reason.

**Comment by mhinz** [comment]
Yup, ag bug: https://github.com/ggreer/the_silver_searcher/issues/1038 :-)

**Comment by amadeus** [comment]
Ahh good to know, thanks!
