### ISSUE TITLE
Grepper goes through hidden directories.

### ISSUE THREAD

**Issue by MeanEYE** [mhinz/vim-grepper#93]
![screenshot from 2017-02-02 14-33-37](https://cloud.githubusercontent.com/assets/1911594/22549563/9a0aa13e-e954-11e6-8f19-41b013ddad14.png)

As seen on the screen shot grepper goes through hidden directories and searches everything finding previous changes in git logs and similar.

**Comment by mhinz** [comment]
Well, that's how `grep` works. :)

If your grep is recent enough, it supports `--exclude-dir`. To add this to the default command run by grep, put this in your vimrc:

```viml
runtime autoload/grepper.vim
let g:grepper.grep.grepprg .= ' --exclude-dir .git'
```

**Comment by MeanEYE** [comment]
![screenshot from 2017-02-02 16-02-02](https://cloud.githubusercontent.com/assets/1911594/22552288/f4c98a66-e960-11e6-8658-3c19e528ba35.png)
Can you please help with this. Grep should be sufficiently new as am on Debian Testing but this is Vim/Grepper specified. Thanks!

**Comment by MeanEYE** [comment]
Never mind. Solved it!
