### ISSUE TITLE
Show results number?

### ISSUE THREAD

**Issue by ahmedelgabri** [mhinz/vim-grepper#95]
One thing I miss in with `-side` results, is the number of matches/files, something like `N matches across N files` or something along these lines on the top of the result buffer. If possible, this would be great!

**Comment by mhinz** [comment]
It's in the &statusline already!

**Comment by ahmedelgabri** [comment]
Oh! I didn't know that because I use airline & it was not shown when I turned airline off it appeared.

Just added

```vim
let g:airline_exclude_filetypes = [
      \ 'GrepperSide'
      \ ]
```
Thanks!
