### ISSUE TITLE
ignoring g:grepper.highlight in operator mode 

### ISSUE THREAD

**Issue by Mephistophiles** [mhinz/vim-grepper#96]
```vim
    nmap gs <plug>(GrepperOperator)
    xmap gs <plug>(GrepperOperator)
```

the results do not highlighted when using this operator, but highlighted when using commands such as GrepperAg.

**Comment by mhinz** [comment]
The actual code is run, but it doesn't work like expected: https://github.com/mhinz/vim-grepper/blob/master/autoload/grepper.vim#L641

I'll look into a workaround. Thanks for bringing this up!

**Comment by mhinz** [comment]
It should work now!

**Comment by Mephistophiles** [comment]
Thank you! Worked
