### ISSUE TITLE
Search results buffer not clearing between searches

### ISSUE THREAD

**Issue by elasticdog** [mhinz/vim-grepper#97]
The "Add lines immediately to qf/loc window" commit (https://github.com/mhinz/vim-grepper/commit/1e9cfd877a242089421eef88b6ca7f1888b03a88) causes vim-grepper's buffer to never clear for me; so if I do more than one search, it just appends the new matches to the end of the quickfix window rather than just showing the new search results. If I revert to the previous commit (https://github.com/mhinz/vim-grepper/commit/de4ab1864e6e381ba73c0f3badf31ce302e15e5e), things work as expected. I'm guessing that was not the intended behavior?

**Comment by mhinz** [comment]
Woah, I wonder how I missed that one.

Thanks for mentioning it. Should be fixed now.

**Comment by elasticdog** [comment]
Works like a charm. Thanks for the crazy-fast response and fix!
