### ISSUE TITLE
Grepping operator creates a query that doesn't return any results

### ISSUE THREAD

**Issue by golergka** [mhinz/vim-grepper#99]
I mapped operator as was descriped in the manual. If I do `gsiw` on a word, the following query appears:

`findstr -rspnc:"$*" *> -- "example_term"`

And I don't get any results. However, if I edit it to be just

`findstr -rspnc:"$*" *> example_term`

(without quotes and dashes), I get correct results. How do I configure operator to create a correct query?

**Comment by mhinz** [comment]
Well, I don't use Windows.. *cough*

So, these changes should be made, right?

1. Change the default of `findstr -rspnc:"$*" *` to `findstr -rspnc:$* *`.
2. Don't add the `--` for the operator.

**Comment by golergka** [comment]
Seems like it should do the trick. At least manually editing it this way makes it work. I think it's specific to `findstr` tool

**Comment by mhinz** [comment]
Oh, I did the commit 2 days ago but forgot to push it.. :-)

Now, you probably always have to put quotes around normal queries as well, even if they don't contain anything special.

**Comment by mhinz** [comment]
In the meanwhile I set up Win 10 in VirtualBox to test this and it seems to work just well.

Thanks for bringing this up!

**Comment by golergka** [comment]
Thanks! Will comment when I will be able to test it (don't use windows for development that often)
